/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var menudata={children:[
{text:"Documentation",url:"de/d6a/md_en_2index.html",children:[
{text:"Introduction",url:"de/d6a/md_en_2index.html",children:[
{text:"I/O-bound Applications and Coroutines",url:"d7/d08/md_en_2userver_2intro__io__bound__coro.html"},
{text:"The Basics",url:"d8/d00/md_en_2userver_2intro.html"},
{text:"Feature Comparison with other Frameworks",url:"da/d26/md_en_2userver_2framework__comparison.html"},
{text:"Supported Platforms",url:"d0/dd5/md_en_2userver_2supported__platforms.html"},
{text:"Configure and Build",url:"d3/da9/md_en_2userver_2tutorial_2build.html"},
{text:"Deploy Environment Specific Configurations",url:"d2/d58/md_en_2userver_2deploy__env.html"},
{text:"Releases, Trunk-based Development and Pull Requests",url:"d0/d7b/md_en_2userver_2development_2releases.html"},
{text:"Roadmap and Changelog",url:"da/d9a/md_en_2userver_2roadmap__and__changelog.html"},
{text:"Frequently Asked Questions",url:"de/d61/md_en_2userver_2faq.html"}]},
{text:"Tutorial",url:"de/d6a/md_en_2index.html",children:[
{text:"Writing your first HTTP server",url:"da/d16/md_en_2userver_2tutorial_2hello__service.html"},
{text:"Writing your own configs server",url:"d4/d95/md_en_2userver_2tutorial_2config__service.html"},
{text:"Production configs and best practices",url:"db/d69/md_en_2userver_2tutorial_2production__service.html"},
{text:"TCP half-duplex server with static configs validation",url:"dc/d93/md_en_2userver_2tutorial_2tcp__service.html"},
{text:"TCP full-duplex server with metrics and Spans",url:"db/db9/md_en_2userver_2tutorial_2tcp__full.html"},
{text:"Pre-caching data from HTTP remote",url:"dc/d8a/md_en_2userver_2tutorial_2http__caching.html"},
{text:"HTTP Flatbuf handler and requests",url:"d8/d91/md_en_2userver_2tutorial_2flatbuf__service.html"},
{text:"gRPC client and service",url:"d6/daa/md_en_2userver_2tutorial_2grpc__service.html"},
{text:"PostgreSQL service",url:"d4/d31/md_en_2userver_2tutorial_2postgres__service.html"},
{text:"MongoDB service",url:"d5/d81/md_en_2userver_2tutorial_2mongo__service.html"},
{text:"Redis service",url:"d3/da2/md_en_2userver_2tutorial_2redis__service.html"},
{text:"Custom Authorization/Authentication via PostgreSQL",url:"da/d24/md_en_2userver_2tutorial_2auth__postgres.html"},
{text:"Writing your WebSocket service",url:"d7/d9e/md_en_2userver_2tutorial_2websocket__service.html"},
{text:"Non-Coroutine Console Tool",url:"d2/dfc/md_en_2userver_2tutorial_2json__to__yaml.html"}]},
{text:"Generic development",url:"de/d6a/md_en_2index.html",children:[
{text:"Component system",url:"dc/dcc/md_en_2userver_2component__system.html",children:[
{text:"Clients",url:"de/d08/group__userver__clients.html"},
{text:"HTTP Handlers",url:"d2/d9b/group__userver__http__handlers.html"},
{text:"Other components",url:"dd/d1c/group__userver__components.html"}]},
{text:"Synchronization Primitives",url:"d6/d6c/md_en_2userver_2synchronization.html"},
{text:"Formats (JSON, YAML, BSON, ...)",url:"d2/d20/md_en_2userver_2formats.html"},
{text:"Logging and Tracing",url:"df/d0c/md_en_2userver_2logging.html"},
{text:"Guide on TaskProcessor Usage",url:"db/d90/md_en_2userver_2task__processors__guide.html"},
{text:"Periodics and DistLocks",url:"d7/dc4/md_en_2userver_2periodics.html"}]},
{text:"Testing and Benchmarking",url:"de/d6a/md_en_2index.html",children:[
{text:"Unit Tests and Benchmarks",url:"d4/d70/md_en_2userver_2testing.html"},
{text:"Functional service tests (testsuite)",url:"df/d07/md_en_2userver_2functional__testing.html"},
{text:"Chaos Testing",url:"de/d74/md_en_2userver_2chaos__testing.html"},
{text:"Profiling context switches",url:"db/d8f/md_en_2userver_2profile__context__switches.html"}]},
{text:"Protocols",url:"de/d6a/md_en_2index.html",children:[
{text:"gRPC",url:"d1/d06/md_en_2userver_2grpc.html"},
{text:"HTTP",url:"de/d6a/md_en_2index.html",children:[
{text:"Client",url:"d5/dee/classclients_1_1http_1_1Client.html"},
{text:"HTTP Server",url:"df/d94/md_en_2userver_2http__server.html"}]},
{text:"RabbitMQ (AMQP 0-9-1) - EXPERIMENTAL",url:"dd/de2/rabbitmq_driver.html"},
{text:"Low level",url:"de/d6a/md_en_2index.html",children:[
{text:"TLS client and server socket",url:"df/d00/classengine_1_1io_1_1TlsWrapper.html"},
{text:"TCP and UDP sockets",url:"dd/dcf/classengine_1_1io_1_1Socket.html"},
{text:"Subprocesses",url:"d9/d4f/classengine_1_1subprocess_1_1ProcessStarter.html"}]}]},
{text:"Runtime service features",url:"de/d6a/md_en_2index.html",children:[
{text:"Dynamic configs",url:"de/d10/md_en_2schemas_2dynamic__configs.html"},
{text:"Changing the log level at runtime",url:"d1/de2/md_en_2userver_2log__level__running__service.html"},
{text:"Inspecting in-flight requests",url:"d8/d7b/md_en_2userver_2requests__in__flight.html"},
{text:"Service Statistics and Metrics (Prometheus/Graphite/...)",url:"d9/dac/md_en_2userver_2service__monitor.html"},
{text:"Memory profiling a production service",url:"d4/d1a/md_en_2userver_2memory__profile__running__service.html"},
{text:"Controlling DNS",url:"dc/d72/md_en_2userver_2dns__control.html"},
{text:"Handling OS signals",url:"df/d4e/md_en_2userver_2os__signals.html"},
{text:"Deadline Propagation",url:"d6/d64/md_en_2userver_2deadline__propagation.html"}]},
{text:"Caches",url:"de/d6a/md_en_2index.html",children:[
{text:"Basics of Caches",url:"d5/d2d/md_en_2userver_2caches.html"},
{text:"Local cache dumps",url:"da/dd6/md_en_2userver_2cache__dumps.html"},
{text:"Caching Component for PostgreSQL",url:"d9/dde/pg_cache.html"},
{text:"Least Recently Used (LRU) Caches and expirable LRU caches",url:"d0/dd8/md_en_2userver_2lru__cache.html"}]},
{text:"PostgreSQL",url:"de/d6a/md_en_2index.html",children:[
{text:"uPg Driver",url:"de/de0/pg_driver.html"},
{text:"uPg: Transactions",url:"db/dd8/pg_transactions.html"},
{text:"uPg: Running queries",url:"da/d1c/pg_run_queries.html"},
{text:"uPg: Working with result sets",url:"db/db5/pg_process_results.html"},
{text:"uPg: Supported data types",url:"d0/d89/pg_types.html"},
{text:"uPg: Typed PostgreSQL results",url:"d2/d2f/pg_user_row_types.html"},
{text:"uPg: Postgres errors",url:"d5/d8e/pg_errors.html"},
{text:"uPg: Cluster topology discovery",url:"da/d75/pg_topology.html"},
{text:"uPg: Mapping a C++ type to PostgreSQL user type",url:"d1/dda/pg_user_types.html",children:[
{text:"uPg: Composite user types",url:"d2/d9e/pg_composite_types.html"},
{text:"uPg: Mapping a C++ enum to PostgreSQL enum type.",url:"de/da8/pg_enum.html"},
{text:"uPg: Range types",url:"d5/d7e/pg_range_types.html"},
{text:"uPg: Arrays",url:"d9/d2d/pg_arrays.html"},
{text:"uPg bytea support",url:"da/d9e/pg_bytea.html"}]}]},
{text:"MySQL",url:"de/d6a/md_en_2index.html",children:[
{text:"MySQL Driver - EXPERIMENTAL",url:"db/d3d/mysql_driver.html"},
{text:"MySQL supported types",url:"d2/d0a/md_en_2userver_2mysql_2supported__types.html"},
{text:"MySQL driver design and implementation details",url:"dd/d32/md_en_2userver_2mysql_2design__and__details.html"}]},
{text:"Non relational databases",url:"de/d6a/md_en_2index.html",children:[
{text:"MongoDB",url:"d7/d65/md_en_2userver_2mongodb.html"},
{text:"Redis",url:"dd/dde/md_en_2userver_2redis.html"},
{text:"ClickHouse Driver",url:"dd/ddb/clickhouse_driver.html"}]},
{text:"Opensource",url:"de/d6a/md_en_2index.html",children:[
{text:"API and ABI stability, versioning",url:"db/d57/md_en_2userver_2development_2stability.html"},
{text:"Driver Writing Guide",url:"de/ddb/md_en_2userver_2driver__guide.html"},
{text:"Publications and Videos",url:"dc/d30/md_en_2userver_2publications.html"},
{text:"Notice to external contributors",url:"d4/dd9/md__2data_2code_2service__template_2third__party_2userver_2CONTRIBUTING.html"},
{text:"Security Policy",url:"d6/d2d/md__2data_2code_2service__template_2third__party_2userver_2SECURITY.html"},
{text:"Security Changelog",url:"db/dde/md_en_2userver_2security__changelog.html"},
{text:"Distributed under Apache-2.0 License",url:"^http://www.apache.org/licenses/LICENSE-2.0"},
{text:"Third Party Code Licenses",url:"db/d7c/md__2data_2code_2service__template_2third__party_2userver_2THIRD__PARTY.html"}]}]},
{text:"API Groups",url:"topics.html"},
{text:"Namespaces",url:"namespaces.html"},
{text:"Reference",url:"usergroup0.html",children:[
{text:"Namespace Members",url:"namespacemembers.html",children:[
{text:"All",url:"namespacemembers.html",children:[
{text:"a",url:"namespacemembers.html#index_a"},
{text:"b",url:"namespacemembers_b.html#index_b"},
{text:"c",url:"namespacemembers_c.html#index_c"},
{text:"d",url:"namespacemembers_d.html#index_d"},
{text:"e",url:"namespacemembers_e.html#index_e"},
{text:"f",url:"namespacemembers_f.html#index_f"},
{text:"g",url:"namespacemembers_g.html#index_g"},
{text:"h",url:"namespacemembers_h.html#index_h"},
{text:"i",url:"namespacemembers_i.html#index_i"},
{text:"j",url:"namespacemembers_j.html#index_j"},
{text:"k",url:"namespacemembers_k.html#index_k"},
{text:"l",url:"namespacemembers_l.html#index_l"},
{text:"m",url:"namespacemembers_m.html#index_m"},
{text:"n",url:"namespacemembers_n.html#index_n"},
{text:"o",url:"namespacemembers_o.html#index_o"},
{text:"p",url:"namespacemembers_p.html#index_p"},
{text:"r",url:"namespacemembers_r.html#index_r"},
{text:"s",url:"namespacemembers_s.html#index_s"},
{text:"t",url:"namespacemembers_t.html#index_t"},
{text:"u",url:"namespacemembers_u.html#index_u"},
{text:"v",url:"namespacemembers_v.html#index_v"},
{text:"w",url:"namespacemembers_w.html#index_w"},
{text:"y",url:"namespacemembers_y.html#index_y"}]},
{text:"Functions",url:"namespacemembers_func.html",children:[
{text:"a",url:"namespacemembers_func.html#index_a"},
{text:"b",url:"namespacemembers_func_b.html#index_b"},
{text:"c",url:"namespacemembers_func_c.html#index_c"},
{text:"d",url:"namespacemembers_func_d.html#index_d"},
{text:"e",url:"namespacemembers_func_e.html#index_e"},
{text:"f",url:"namespacemembers_func_f.html#index_f"},
{text:"g",url:"namespacemembers_func_g.html#index_g"},
{text:"h",url:"namespacemembers_func_h.html#index_h"},
{text:"i",url:"namespacemembers_func_i.html#index_i"},
{text:"j",url:"namespacemembers_func_j.html#index_j"},
{text:"k",url:"namespacemembers_func_k.html#index_k"},
{text:"l",url:"namespacemembers_func_l.html#index_l"},
{text:"m",url:"namespacemembers_func_m.html#index_m"},
{text:"n",url:"namespacemembers_func_n.html#index_n"},
{text:"o",url:"namespacemembers_func_o.html#index_o"},
{text:"p",url:"namespacemembers_func_p.html#index_p"},
{text:"r",url:"namespacemembers_func_r.html#index_r"},
{text:"s",url:"namespacemembers_func_s.html#index_s"},
{text:"t",url:"namespacemembers_func_t.html#index_t"},
{text:"u",url:"namespacemembers_func_u.html#index_u"},
{text:"w",url:"namespacemembers_func_w.html#index_w"},
{text:"y",url:"namespacemembers_func_y.html#index_y"}]},
{text:"Variables",url:"namespacemembers_vars.html"},
{text:"Typedefs",url:"namespacemembers_type.html",children:[
{text:"c",url:"namespacemembers_type.html#index_c"},
{text:"d",url:"namespacemembers_type.html#index_d"},
{text:"h",url:"namespacemembers_type.html#index_h"},
{text:"m",url:"namespacemembers_type.html#index_m"},
{text:"n",url:"namespacemembers_type.html#index_n"},
{text:"o",url:"namespacemembers_type.html#index_o"},
{text:"p",url:"namespacemembers_type.html#index_p"},
{text:"s",url:"namespacemembers_type.html#index_s"},
{text:"t",url:"namespacemembers_type.html#index_t"},
{text:"u",url:"namespacemembers_type.html#index_u"},
{text:"v",url:"namespacemembers_type.html#index_v"}]},
{text:"Enumerations",url:"namespacemembers_enum.html",children:[
{text:"a",url:"namespacemembers_enum.html#index_a"},
{text:"b",url:"namespacemembers_enum.html#index_b"},
{text:"c",url:"namespacemembers_enum.html#index_c"},
{text:"d",url:"namespacemembers_enum.html#index_d"},
{text:"f",url:"namespacemembers_enum.html#index_f"},
{text:"h",url:"namespacemembers_enum.html#index_h"},
{text:"i",url:"namespacemembers_enum.html#index_i"},
{text:"l",url:"namespacemembers_enum.html#index_l"},
{text:"o",url:"namespacemembers_enum.html#index_o"},
{text:"p",url:"namespacemembers_enum.html#index_p"},
{text:"r",url:"namespacemembers_enum.html#index_r"},
{text:"s",url:"namespacemembers_enum.html#index_s"},
{text:"t",url:"namespacemembers_enum.html#index_t"},
{text:"u",url:"namespacemembers_enum.html#index_u"},
{text:"v",url:"namespacemembers_enum.html#index_v"}]}]},
{text:"Class List",url:"annotated.html"},
{text:"Class Index",url:"classes.html"},
{text:"Class Hierarchy",url:"inherits.html"},
{text:"Class Members",url:"functions.html",children:[
{text:"All",url:"functions.html",children:[
{text:"_",url:"functions.html#index__5F"},
{text:"a",url:"functions_a.html#index_a"},
{text:"b",url:"functions_b.html#index_b"},
{text:"c",url:"functions_c.html#index_c"},
{text:"d",url:"functions_d.html#index_d"},
{text:"e",url:"functions_e.html#index_e"},
{text:"f",url:"functions_f.html#index_f"},
{text:"g",url:"functions_g.html#index_g"},
{text:"h",url:"functions_h.html#index_h"},
{text:"i",url:"functions_i.html#index_i"},
{text:"k",url:"functions_k.html#index_k"},
{text:"l",url:"functions_l.html#index_l"},
{text:"m",url:"functions_m.html#index_m"},
{text:"n",url:"functions_n.html#index_n"},
{text:"o",url:"functions_o.html#index_o"},
{text:"p",url:"functions_p.html#index_p"},
{text:"q",url:"functions_q.html#index_q"},
{text:"r",url:"functions_r.html#index_r"},
{text:"s",url:"functions_s.html#index_s"},
{text:"t",url:"functions_t.html#index_t"},
{text:"u",url:"functions_u.html#index_u"},
{text:"v",url:"functions_v.html#index_v"},
{text:"w",url:"functions_w.html#index_w"},
{text:"y",url:"functions_y.html#index_y"},
{text:"~",url:"functions_~.html#index__7E"}]},
{text:"Functions",url:"functions_func.html",children:[
{text:"_",url:"functions_func.html#index__5F"},
{text:"a",url:"functions_func_a.html#index_a"},
{text:"b",url:"functions_func_b.html#index_b"},
{text:"c",url:"functions_func_c.html#index_c"},
{text:"d",url:"functions_func_d.html#index_d"},
{text:"e",url:"functions_func_e.html#index_e"},
{text:"f",url:"functions_func_f.html#index_f"},
{text:"g",url:"functions_func_g.html#index_g"},
{text:"h",url:"functions_func_h.html#index_h"},
{text:"i",url:"functions_func_i.html#index_i"},
{text:"k",url:"functions_func_k.html#index_k"},
{text:"l",url:"functions_func_l.html#index_l"},
{text:"m",url:"functions_func_m.html#index_m"},
{text:"n",url:"functions_func_n.html#index_n"},
{text:"o",url:"functions_func_o.html#index_o"},
{text:"p",url:"functions_func_p.html#index_p"},
{text:"q",url:"functions_func_q.html#index_q"},
{text:"r",url:"functions_func_r.html#index_r"},
{text:"s",url:"functions_func_s.html#index_s"},
{text:"t",url:"functions_func_t.html#index_t"},
{text:"u",url:"functions_func_u.html#index_u"},
{text:"v",url:"functions_func_v.html#index_v"},
{text:"w",url:"functions_func_w.html#index_w"},
{text:"y",url:"functions_func_y.html#index_y"},
{text:"~",url:"functions_func_~.html#index__7E"}]},
{text:"Variables",url:"functions_vars.html",children:[
{text:"a",url:"functions_vars.html#index_a"},
{text:"b",url:"functions_vars_b.html#index_b"},
{text:"c",url:"functions_vars_c.html#index_c"},
{text:"d",url:"functions_vars_d.html#index_d"},
{text:"e",url:"functions_vars_e.html#index_e"},
{text:"f",url:"functions_vars_f.html#index_f"},
{text:"g",url:"functions_vars_g.html#index_g"},
{text:"h",url:"functions_vars_h.html#index_h"},
{text:"i",url:"functions_vars_i.html#index_i"},
{text:"k",url:"functions_vars_k.html#index_k"},
{text:"l",url:"functions_vars_l.html#index_l"},
{text:"m",url:"functions_vars_m.html#index_m"},
{text:"n",url:"functions_vars_n.html#index_n"},
{text:"o",url:"functions_vars_o.html#index_o"},
{text:"p",url:"functions_vars_p.html#index_p"},
{text:"q",url:"functions_vars_q.html#index_q"},
{text:"r",url:"functions_vars_r.html#index_r"},
{text:"s",url:"functions_vars_s.html#index_s"},
{text:"t",url:"functions_vars_t.html#index_t"},
{text:"u",url:"functions_vars_u.html#index_u"},
{text:"v",url:"functions_vars_v.html#index_v"},
{text:"w",url:"functions_vars_w.html#index_w"}]},
{text:"Typedefs",url:"functions_type.html"},
{text:"Enumerations",url:"functions_enum.html"},
{text:"Enumerator",url:"functions_eval.html"},
{text:"Related Symbols",url:"functions_rela.html"}]},
{text:"File List",url:"files.html"},
{text:"File Members",url:"globals.html",children:[
{text:"All",url:"globals.html",children:[
{text:"e",url:"globals.html#index_e"},
{text:"i",url:"globals.html#index_i"},
{text:"l",url:"globals.html#index_l"},
{text:"r",url:"globals.html#index_r"},
{text:"t",url:"globals.html#index_t"},
{text:"u",url:"globals.html#index_u"}]},
{text:"Functions",url:"globals_func.html"},
{text:"Macros",url:"globals_defs.html",children:[
{text:"e",url:"globals_defs.html#index_e"},
{text:"i",url:"globals_defs.html#index_i"},
{text:"l",url:"globals_defs.html#index_l"},
{text:"r",url:"globals_defs.html#index_r"},
{text:"t",url:"globals_defs.html#index_t"},
{text:"u",url:"globals_defs.html#index_u"}]}]},
{text:"Examples",url:"examples.html"}]}]}
