var searchData=
[
  ['data_20from_20http_20remote_0',['Pre-caching data from HTTP remote',['../dc/d8a/md_en_2userver_2tutorial_2http__caching.html',1,'']]],
  ['data_20types_1',['uPg: Supported data types',['../d0/d89/pg_types.html',1,'']]],
  ['deadline_20propagation_2',['Deadline propagation',['../d6/d64/md_en_2userver_2deadline__propagation.html',1,'']]],
  ['debian_2011x32_3',['debian-11x32',['../d2/d57/md_en_2deps_2debian-11x32.html',1,'']]],
  ['deploy_20environment_20specific_20configurations_4',['Deploy Environment Specific Configurations',['../d2/d58/md_en_2userver_2deploy__env.html',1,'']]],
  ['deprecated_20list_5',['Deprecated List',['../da/d58/deprecated.html',1,'']]],
  ['design_20and_20implementation_20details_6',['MySQL driver design and implementation details',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html',1,'']]],
  ['details_7',['MySQL driver design and implementation details',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html',1,'']]],
  ['development_20and_20pull_20requests_8',['Releases, Trunk-based Development and Pull Requests',['../d0/d7b/md_en_2userver_2development_2releases.html',1,'']]],
  ['digest_20authorization_20authentication_20via_20postgresql_9',['Digest Authorization/Authentication via PostgreSQL',['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html',1,'']]],
  ['discovery_10',['uPg: Cluster topology discovery',['../da/d75/pg_topology.html',1,'']]],
  ['distlocks_11',['Periodics and DistLocks',['../d7/dc4/md_en_2userver_2periodics.html',1,'']]],
  ['dns_12',['Controlling DNS',['../dc/d72/md_en_2userver_2dns__control.html',1,'']]],
  ['docker_20for_20userver_13',['Docker for userver',['../d8/df2/md_en_2userver_2docker.html',1,'']]],
  ['driver_14',['driver',['../dd/ddb/clickhouse_driver.html',1,'ClickHouse Driver'],['../de/de0/pg_driver.html',1,'uPg Driver']]],
  ['driver_20design_20and_20implementation_20details_15',['MySQL driver design and implementation details',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html',1,'']]],
  ['driver_20experimental_16',['MySQL Driver - EXPERIMENTAL',['../db/d3d/mysql_driver.html',1,'']]],
  ['driver_20writing_20guide_17',['Driver Writing Guide',['../de/ddb/md_en_2userver_2driver__guide.html',1,'']]],
  ['dumps_18',['Local cache dumps',['../da/dd6/md_en_2userver_2cache__dumps.html',1,'']]],
  ['duplex_20server_20with_20metrics_20and_20spans_19',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['duplex_20server_20with_20static_20configs_20validation_20',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['dynamic_20configs_21',['Dynamic configs',['../de/d10/md_en_2schemas_2dynamic__configs.html',1,'']]]
];
