var searchData=
[
  ['rabbitendpoints_0',['RabbitEndpoints',['../dd/dba/structurabbitmq_1_1RabbitEndpoints.html',1,'urabbitmq']]],
  ['rabbitendpointsmulti_1',['RabbitEndpointsMulti',['../d3/d74/classurabbitmq_1_1RabbitEndpointsMulti.html',1,'urabbitmq']]],
  ['rabbitmq_2',['RabbitMQ',['../d5/d23/classcomponents_1_1RabbitMQ.html',1,'components']]],
  ['randombase_3',['RandomBase',['../d1/d26/classutils_1_1RandomBase.html',1,'utils']]],
  ['range_4',['Range',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['range_3c_20bigint_20_3e_5',['Range&lt; Bigint &gt;',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['range_3c_20integer_20_3e_6',['Range&lt; Integer &gt;',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['rangeoptions_7',['RangeOptions',['../d7/de0/structstorages_1_1redis_1_1RangeOptions.html',1,'storages::redis']]],
  ['rangescoreoptions_8',['RangeScoreOptions',['../dc/d5d/structstorages_1_1redis_1_1RangeScoreOptions.html',1,'storages::redis']]],
  ['rate_9',['Rate',['../d2/d1b/structutils_1_1statistics_1_1Rate.html',1,'utils::statistics']]],
  ['ratecounter_10',['RateCounter',['../da/d24/classutils_1_1statistics_1_1RateCounter.html',1,'utils::statistics']]],
  ['rawcomponentbase_11',['RawComponentBase',['../d2/d86/classcomponents_1_1RawComponentBase.html',1,'components']]],
  ['rcumap_12',['RcuMap',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20concurrent_3a_3avariable_3c_20server_3a_3ahandlers_3a_3aauth_3a_3adigest_3a_3anonceinfo_20_3e_20_3e_13',['RcuMap&lt; std::string, concurrent::Variable&lt; server::handlers::auth::digest::NonceInfo &gt; &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20const_20fs_3a_3afileinfowithdata_20_3e_14',['RcuMap&lt; std::string, const fs::FileInfoWithData &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20logging_3a_3aloggerptr_20_3e_15',['RcuMap&lt; std::string, logging::LoggerPtr &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumapiterator_16',['RcuMapIterator',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['rcumapiterator_3c_20key_2c_20value_2c_20const_20value_2c_20rcumaptraits_20_3e_17',['RcuMapIterator&lt; Key, Value, const Value, RcuMapTraits &gt;',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['rcumapiterator_3c_20key_2c_20value_2c_20value_2c_20rcumaptraits_20_3e_18',['RcuMapIterator&lt; Key, Value, Value, RcuMapTraits &gt;',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['re2replacement_19',['Re2Replacement',['../d2/d93/structutils_1_1Re2Replacement.html',1,'utils']]],
  ['readablebase_20',['ReadableBase',['../da/d1b/classengine_1_1io_1_1ReadableBase.html',1,'engine::io']]],
  ['readableptr_21',['ReadablePtr',['../dd/df3/classrcu_1_1ReadablePtr.html',1,'rcu']]],
  ['readableptr_3c_20engine_3a_3asubprocess_3a_3aenvironmentvariables_20_3e_22',['ReadablePtr&lt; engine::subprocess::EnvironmentVariables &gt;',['../dd/df3/classrcu_1_1ReadablePtr.html',1,'rcu']]],
  ['reader_23',['Reader',['../d2/d03/classdump_1_1Reader.html',1,'dump::Reader'],['../d7/d9d/classugrpc_1_1client_1_1Reader.html',1,'ugrpc::client::Reader&lt; Response &gt;'],['../db/dd8/classugrpc_1_1server_1_1Reader.html',1,'ugrpc::server::Reader&lt; Request &gt;']]],
  ['readerwriter_24',['ReaderWriter',['../d8/d9b/classugrpc_1_1client_1_1ReaderWriter.html',1,'ugrpc::client::ReaderWriter&lt; Request, Response &gt;'],['../dc/db1/classugrpc_1_1server_1_1ReaderWriter.html',1,'ugrpc::server::ReaderWriter&lt; Request, Response &gt;']]],
  ['readerwriter_3c_20grpc_3a_3abytebuffer_2c_20grpc_3a_3abytebuffer_20_3e_25',['ReaderWriter&lt; grpc::ByteBuffer, grpc::ByteBuffer &gt;',['../dc/db1/classugrpc_1_1server_1_1ReaderWriter.html',1,'ugrpc::server']]],
  ['readonlystrategy_26',['ReadOnlyStrategy',['../d1/d8c/classstorages_1_1sqlite_1_1infra_1_1strategy_1_1ReadOnlyStrategy.html',1,'storages::sqlite::infra::strategy']]],
  ['readpreference_27',['ReadPreference',['../dc/db5/classstorages_1_1mongo_1_1options_1_1ReadPreference.html',1,'storages::mongo::options']]],
  ['readtableresults_28',['ReadTableResults',['../d4/d81/classydb_1_1ReadTableResults.html',1,'ydb']]],
  ['readwritestrategy_29',['ReadWriteStrategy',['../df/df1/classstorages_1_1sqlite_1_1infra_1_1strategy_1_1ReadWriteStrategy.html',1,'storages::sqlite::infra::strategy']]],
  ['recentperiod_30',['RecentPeriod',['../d2/d67/classutils_1_1statistics_1_1RecentPeriod.html',1,'utils::statistics']]],
  ['recvfromresult_31',['RecvFromResult',['../dc/d72/structengine_1_1io_1_1Socket_1_1RecvFromResult.html',1,'engine::io::Socket']]],
  ['redis_32',['Redis',['../d6/dd0/classcomponents_1_1Redis.html',1,'components']]],
  ['rediscontrol_33',['RedisControl',['../d4/dfe/structtestsuite_1_1RedisControl.html',1,'testsuite']]],
  ['redislocal_34',['RedisLocal',['../df/d18/classstorages_1_1redis_1_1utest_1_1RedisLocal.html',1,'storages::redis::utest']]],
  ['redistest_35',['RedisTest',['../d8/d84/classstorages_1_1redis_1_1utest_1_1RedisTest.html',1,'storages::redis::utest']]],
  ['rediswaitconnected_36',['RedisWaitConnected',['../d5/d66/structstorages_1_1redis_1_1RedisWaitConnected.html',1,'storages::redis']]],
  ['refillpolicy_37',['RefillPolicy',['../de/d15/structutils_1_1TokenBucket_1_1RefillPolicy.html',1,'utils::TokenBucket']]],
  ['reflectionservicecomponent_38',['ReflectionServiceComponent',['../d1/ddc/classgrpc__reflection_1_1ReflectionServiceComponent.html',1,'grpc_reflection']]],
  ['regex_39',['regex',['../dd/d3e/classutils_1_1regex.html',1,'utils']]],
  ['regexerror_40',['RegexError',['../d1/dc0/classutils_1_1RegexError.html',1,'utils']]],
  ['registeredntrx_41',['RegisteredNtrx',['../dc/d90/classpytest__userver_1_1plugins_1_1postgresql_1_1RegisteredNtrx.html',1,'pytest_userver::plugins::postgresql']]],
  ['registeredntrxfailuretype_42',['RegisteredNtrxFailureType',['../d3/dad/classpytest__userver_1_1plugins_1_1postgresql_1_1RegisteredNtrxFailureType.html',1,'pytest_userver::plugins::postgresql']]],
  ['registeredtrx_43',['RegisteredTrx',['../d2/dd0/classpytest__userver_1_1sql_1_1RegisteredTrx.html',1,'pytest_userver::sql']]],
  ['relaxedcounter_44',['RelaxedCounter',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['relaxedcounter_3c_20size_5ft_20_3e_45',['RelaxedCounter&lt; size_t &gt;',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['reliablechannel_46',['ReliableChannel',['../db/deb/classurabbitmq_1_1ReliableChannel.html',1,'urabbitmq']]],
  ['removetuplereferences_47',['RemoveTupleReferences',['../d1/d86/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences.html',1,'storages::postgres::io::traits']]],
  ['removetuplereferences_3c_20std_3a_3atuple_3c_20t_2e_2e_2e_20_3e_20_3e_48',['RemoveTupleReferences&lt; std::tuple&lt; T... &gt; &gt;',['../d7/dd1/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html',1,'storages::postgres::io::traits']]],
  ['replaceone_49',['ReplaceOne',['../d4/d75/classstorages_1_1mongo_1_1bulk__ops_1_1ReplaceOne.html',1,'storages::mongo::bulk_ops::ReplaceOne'],['../d5/de4/classstorages_1_1mongo_1_1operations_1_1ReplaceOne.html',1,'storages::mongo::operations::ReplaceOne']]],
  ['replicationmonitoringsettings_50',['ReplicationMonitoringSettings',['../d7/d85/structstorages_1_1redis_1_1ReplicationMonitoringSettings.html',1,'storages::redis']]],
  ['reply_51',['Reply',['../d7/dc1/structdynamic__config_1_1Client_1_1Reply.html',1,'dynamic_config::Client::Reply'],['../d3/d48/classstorages_1_1redis_1_1Reply.html',1,'storages::redis::Reply']]],
  ['replydata_52',['ReplyData',['../da/d08/classstorages_1_1redis_1_1ReplyData.html',1,'storages::redis']]],
  ['replyelemholder_53',['ReplyElemHolder',['../dc/da7/classstorages_1_1redis_1_1ScanRequest_1_1Iterator_1_1ReplyElemHolder.html',1,'storages::redis::ScanRequest::Iterator']]],
  ['request_54',['Request',['../de/df5/classclients_1_1http_1_1Request.html',1,'clients::http::Request'],['../d9/d8d/structs3api_1_1Request.html',1,'s3api::Request'],['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis::Request&lt; ResultType, ReplyType &gt;'],['../da/dc2/classutils_1_1statistics_1_1Request.html',1,'utils::statistics::Request']]],
  ['request_3c_20double_20_3e_55',['Request&lt; double &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20expirereply_20_3e_56',['Request&lt; ExpireReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20hsetreply_20_3e_57',['Request&lt; HsetReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20int64_5ft_20_3e_58',['Request&lt; int64_t &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20keytype_20_3e_59',['Request&lt; KeyType &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20persistreply_20_3e_60',['Request&lt; PersistReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20replydata_20_3e_61',['Request&lt; ReplyData &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20replydata_2c_20void_20_3e_62',['Request&lt; ReplyData, void &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20setreply_20_3e_63',['Request&lt; SetReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20size_5ft_20_3e_64',['Request&lt; size_t &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20size_5ft_2c_20bool_20_3e_65',['Request&lt; size_t, bool &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20statusok_2c_20void_20_3e_66',['Request&lt; StatusOk, void &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20statuspong_2c_20void_20_3e_67',['Request&lt; StatusPong, void &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3achrono_3a_3asystem_5fclock_3a_3atime_5fpoint_20_3e_68',['Request&lt; std::chrono::system_clock::time_point &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aoptional_3c_20double_20_3e_20_3e_69',['Request&lt; std::optional&lt; double &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aoptional_3c_20statusok_20_3e_2c_20bool_20_3e_70',['Request&lt; std::optional&lt; StatusOk &gt;, bool &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aoptional_3c_20std_3a_3astring_20_3e_20_3e_71',['Request&lt; std::optional&lt; std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3astring_20_3e_72',['Request&lt; std::string &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aunordered_5fmap_3c_20std_3a_3astring_2c_20std_3a_3astring_20_3e_20_3e_73',['Request&lt; std::unordered_map&lt; std::string, std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aunordered_5fset_3c_20std_3a_3astring_20_3e_20_3e_74',['Request&lt; std::unordered_set&lt; std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20geopoint_20_3e_20_3e_75',['Request&lt; std::vector&lt; GeoPoint &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20memberscore_20_3e_20_3e_76',['Request&lt; std::vector&lt; MemberScore &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20std_3a_3aoptional_3c_20std_3a_3astring_20_3e_20_3e_20_3e_77',['Request&lt; std::vector&lt; std::optional&lt; std::string &gt; &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20std_3a_3astring_20_3e_20_3e_78',['Request&lt; std::vector&lt; std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20ttlreply_20_3e_79',['Request&lt; TtlReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['requestcancelledexception_80',['RequestCancelledException',['../d0/d73/classstorages_1_1redis_1_1RequestCancelledException.html',1,'storages::redis']]],
  ['requestcontext_81',['RequestContext',['../de/df6/classserver_1_1request_1_1RequestContext.html',1,'server::request']]],
  ['requestdatabase_82',['RequestDataBase',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requesteval_83',['RequestEval',['../df/d69/classstorages_1_1redis_1_1RequestEval.html',1,'storages::redis']]],
  ['requestevalsha_84',['RequestEvalSha',['../d5/daf/classstorages_1_1redis_1_1RequestEvalSha.html',1,'storages::redis']]],
  ['requestfailedexception_85',['RequestFailedException',['../d0/d0c/classstorages_1_1redis_1_1RequestFailedException.html',1,'storages::redis']]],
  ['requestgeneric_86',['RequestGeneric',['../df/d89/classstorages_1_1redis_1_1RequestGeneric.html',1,'storages::redis']]],
  ['requestparseerror_87',['RequestParseError',['../d4/ddf/classserver_1_1handlers_1_1RequestParseError.html',1,'server::handlers']]],
  ['requestscandata_88',['RequestScanData',['../d7/dbd/classstorages_1_1redis_1_1RequestScanData.html',1,'storages::redis']]],
  ['requestscandatabase_89',['RequestScanDataBase',['../da/d20/classstorages_1_1redis_1_1RequestScanDataBase.html',1,'storages::redis']]],
  ['requestssource_90',['RequestsSource',['../d1/dc2/classserver_1_1congestion__control_1_1RequestsSource.html',1,'server::congestion_control']]],
  ['requesttraits_91',['RequestTraits',['../d7/d18/structutils_1_1hedging_1_1RequestTraits.html',1,'utils::hedging']]],
  ['resolver_92',['Resolver',['../d0/d75/classclients_1_1dns_1_1Resolver.html',1,'clients::dns']]],
  ['resolverexception_93',['ResolverException',['../d8/d54/classclients_1_1dns_1_1ResolverException.html',1,'clients::dns']]],
  ['resourceexhaustederror_94',['ResourceExhaustedError',['../d8/db2/classugrpc_1_1client_1_1ResourceExhaustedError.html',1,'ugrpc::client']]],
  ['resourcenotfound_95',['ResourceNotFound',['../d2/d91/classserver_1_1handlers_1_1ResourceNotFound.html',1,'server::handlers']]],
  ['response_96',['Response',['../dd/d3b/classclients_1_1http_1_1Response.html',1,'clients::http::Response'],['../d8/d24/structutest_1_1SimpleServer_1_1Response.html',1,'utest::SimpleServer::Response']]],
  ['responsebase_97',['ResponseBase',['../d3/dee/classserver_1_1request_1_1ResponseBase.html',1,'server::request']]],
  ['responsebodystream_98',['ResponseBodyStream',['../dd/d63/classserver_1_1http_1_1ResponseBodyStream.html',1,'server::http']]],
  ['responsedataaccounter_99',['ResponseDataAccounter',['../d0/d6f/classserver_1_1request_1_1ResponseDataAccounter.html',1,'server::request']]],
  ['responseerror_100',['ResponseError',['../d6/db8/classgrpc__protovalidate_1_1client_1_1ResponseError.html',1,'grpc_protovalidate::client']]],
  ['responsefuture_101',['ResponseFuture',['../d0/d9b/classclients_1_1http_1_1ResponseFuture.html',1,'clients::http::ResponseFuture'],['../d6/d3b/classugrpc_1_1client_1_1ResponseFuture.html',1,'ugrpc::client::ResponseFuture&lt; Response &gt;']]],
  ['responsetruncatederror_102',['ResponseTruncatedError',['../db/dcc/classydb_1_1ResponseTruncatedError.html',1,'ydb']]],
  ['restart_103',['Restart',['../dc/d53/classserver_1_1handlers_1_1Restart.html',1,'server::handlers']]],
  ['restrictviolation_104',['RestrictViolation',['../d9/daa/classstorages_1_1postgres_1_1RestrictViolation.html',1,'storages::postgres']]],
  ['result_105',['Result',['../d9/d97/classugrpc_1_1server_1_1Result.html',1,'ugrpc::server']]],
  ['resultset_106',['ResultSet',['../d0/d5b/classstorages_1_1postgres_1_1ResultSet.html',1,'storages::postgres::ResultSet'],['../dc/da3/classstorages_1_1sqlite_1_1ResultSet.html',1,'storages::sqlite::ResultSet']]],
  ['resultseterror_107',['ResultSetError',['../d5/d9d/classstorages_1_1postgres_1_1ResultSetError.html',1,'storages::postgres']]],
  ['resultstore_108',['ResultStore',['../d9/d54/classutils_1_1ResultStore.html',1,'utils']]],
  ['resultstore_3c_20void_20_3e_109',['ResultStore&lt; void &gt;',['../dc/db9/classutils_1_1ResultStore_3_01void_01_4.html',1,'utils']]],
  ['retrybudget_110',['RetryBudget',['../d5/d9f/classutils_1_1RetryBudget.html',1,'utils']]],
  ['retrybudgetsettings_111',['RetryBudgetSettings',['../d4/df0/structutils_1_1RetryBudgetSettings.html',1,'utils']]],
  ['retryconfig_112',['RetryConfig',['../d3/daa/structugrpc_1_1client_1_1RetryConfig.html',1,'ugrpc::client']]],
  ['retryduplicatekey_113',['RetryDuplicateKey',['../d8/d28/classstorages_1_1mongo_1_1options_1_1RetryDuplicateKey.html',1,'storages::mongo::options']]],
  ['retrynilfrommaster_114',['RetryNilFromMaster',['../d9/d6d/structstorages_1_1redis_1_1RetryNilFromMaster.html',1,'storages::redis']]],
  ['returnnew_115',['ReturnNew',['../df/d9c/classstorages_1_1mongo_1_1options_1_1ReturnNew.html',1,'storages::mongo::options']]],
  ['reverseconstfielditerator_116',['ReverseConstFieldIterator',['../d1/d69/classstorages_1_1postgres_1_1ReverseConstFieldIterator.html',1,'storages::postgres']]],
  ['reverseconstrowiterator_117',['ReverseConstRowIterator',['../d6/d82/classstorages_1_1postgres_1_1ReverseConstRowIterator.html',1,'storages::postgres']]],
  ['rounddownroundpolicy_118',['RoundDownRoundPolicy',['../dd/d4c/classdecimal64_1_1RoundDownRoundPolicy.html',1,'decimal64']]],
  ['rounduproundpolicy_119',['RoundUpRoundPolicy',['../de/dc3/classdecimal64_1_1RoundUpRoundPolicy.html',1,'decimal64']]],
  ['row_120',['Row',['../db/dfe/classstorages_1_1postgres_1_1Row.html',1,'storages::postgres::Row'],['../dc/db6/classydb_1_1Row.html',1,'ydb::Row']]],
  ['rowcategory_121',['RowCategory',['../d3/d4b/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory.html',1,'storages::postgres::io::traits']]],
  ['rowcategory_3c_3a_3autils_3a_3astrongtypedef_3c_20tag_2c_20t_2c_20ops_2c_20enable_20_3e_20_3e_122',['RowCategory&lt;::utils::StrongTypedef&lt; Tag, T, Ops, Enable &gt; &gt;',['../da/d9a/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory_3_1_1utils_1_1StrongTypedef_3_01Tag_00a475f9e72ca0f19000d262961377c32b.html',1,'storages::postgres::io::traits']]],
  ['rowdescription_123',['RowDescription',['../d1/d9f/classstorages_1_1postgres_1_1RowDescription.html',1,'storages::postgres']]],
  ['rowindexoutofbounds_124',['RowIndexOutOfBounds',['../db/dea/classstorages_1_1postgres_1_1RowIndexOutOfBounds.html',1,'storages::postgres']]],
  ['rowsmapper_125',['RowsMapper',['../d8/d1d/classstorages_1_1clickhouse_1_1io_1_1RowsMapper.html',1,'storages::clickhouse::io']]],
  ['rowtag_126',['RowTag',['../d6/d4d/structstorages_1_1mysql_1_1RowTag.html',1,'storages::mysql::RowTag'],['../df/d46/structstorages_1_1postgres_1_1RowTag.html',1,'storages::postgres::RowTag'],['../df/d2b/structstorages_1_1sqlite_1_1RowTag.html',1,'storages::sqlite::RowTag']]],
  ['rowtype_127',['RowType',['../d4/dce/structstorages_1_1postgres_1_1io_1_1RowType.html',1,'storages::postgres::io']]],
  ['rpccancellederror_128',['RpcCancelledError',['../d8/ddb/classugrpc_1_1client_1_1RpcCancelledError.html',1,'ugrpc::client']]],
  ['rpcerror_129',['RpcError',['../d3/d28/classugrpc_1_1client_1_1RpcError.html',1,'ugrpc::client::RpcError'],['../db/d1c/classugrpc_1_1server_1_1RpcError.html',1,'ugrpc::server::RpcError']]],
  ['rpcinterruptederror_130',['RpcInterruptedError',['../db/d86/classugrpc_1_1client_1_1RpcInterruptedError.html',1,'ugrpc::client::RpcInterruptedError'],['../d0/dd9/classugrpc_1_1server_1_1RpcInterruptedError.html',1,'ugrpc::server::RpcInterruptedError']]],
  ['runnercomponentbase_131',['RunnerComponentBase',['../d7/dd1/classmiddlewares_1_1RunnerComponentBase.html',1,'middlewares']]],
  ['runnercomponentbase_3c_20middlewarebase_2c_20clientinfo_20_3e_132',['RunnerComponentBase&lt; MiddlewareBase, ClientInfo &gt;',['../d7/dd1/classmiddlewares_1_1RunnerComponentBase.html',1,'middlewares']]],
  ['runnercomponentbase_3c_20middlewarebase_2c_20serviceinfo_20_3e_133',['RunnerComponentBase&lt; MiddlewareBase, ServiceInfo &gt;',['../d7/dd1/classmiddlewares_1_1RunnerComponentBase.html',1,'middlewares']]],
  ['runtimeerror_134',['RuntimeError',['../d6/d97/classstorages_1_1postgres_1_1RuntimeError.html',1,'storages::postgres']]],
  ['rwbase_135',['RwBase',['../d3/d1e/classengine_1_1io_1_1RwBase.html',1,'engine::io']]]
];
