var searchData=
[
  ['rabbitendpoints_0',['RabbitEndpoints',['../dd/dba/structurabbitmq_1_1RabbitEndpoints.html',1,'urabbitmq']]],
  ['rabbitendpointsmulti_1',['RabbitEndpointsMulti',['../d3/d74/classurabbitmq_1_1RabbitEndpointsMulti.html',1,'urabbitmq']]],
  ['rabbitmq_2',['RabbitMQ',['../d5/d23/classcomponents_1_1RabbitMQ.html',1,'components']]],
  ['randombase_3',['RandomBase',['../d1/d26/classutils_1_1RandomBase.html',1,'utils']]],
  ['range_4',['Range',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['range_3c_20bigint_20_3e_5',['Range&lt; Bigint &gt;',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['range_3c_20integer_20_3e_6',['Range&lt; Integer &gt;',['../d1/df6/classstorages_1_1postgres_1_1Range.html',1,'storages::postgres']]],
  ['rangeoptions_7',['RangeOptions',['../d7/de0/structstorages_1_1redis_1_1RangeOptions.html',1,'storages::redis']]],
  ['rangescoreoptions_8',['RangeScoreOptions',['../dc/d5d/structstorages_1_1redis_1_1RangeScoreOptions.html',1,'storages::redis']]],
  ['rate_9',['Rate',['../d2/d1b/structutils_1_1statistics_1_1Rate.html',1,'utils::statistics']]],
  ['ratecounter_10',['RateCounter',['../da/d24/classutils_1_1statistics_1_1RateCounter.html',1,'utils::statistics']]],
  ['rawanydata_11',['RawAnyData',['../da/d31/structprotobuf_1_1json_1_1tests_1_1RawAnyData.html',1,'protobuf::json::tests']]],
  ['rawcomponentbase_12',['RawComponentBase',['../d2/d86/classcomponents_1_1RawComponentBase.html',1,'components']]],
  ['rcumap_13',['RcuMap',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20concurrent_3a_3avariable_3c_20server_3a_3ahandlers_3a_3aauth_3a_3adigest_3a_3anonceinfo_20_3e_20_3e_14',['RcuMap&lt; std::string, concurrent::Variable&lt; server::handlers::auth::digest::NonceInfo &gt; &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20const_20fs_3a_3afileinfowithdata_20_3e_15',['RcuMap&lt; std::string, const fs::FileInfoWithData &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumap_3c_20std_3a_3astring_2c_20logging_3a_3aloggerptr_20_3e_16',['RcuMap&lt; std::string, logging::LoggerPtr &gt;',['../d0/d1f/classrcu_1_1RcuMap.html',1,'rcu']]],
  ['rcumapiterator_17',['RcuMapIterator',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['rcumapiterator_3c_20key_2c_20value_2c_20const_20value_2c_20rcumaptraits_20_3e_18',['RcuMapIterator&lt; Key, Value, const Value, RcuMapTraits &gt;',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['rcumapiterator_3c_20key_2c_20value_2c_20value_2c_20rcumaptraits_20_3e_19',['RcuMapIterator&lt; Key, Value, Value, RcuMapTraits &gt;',['../d8/de4/classrcu_1_1RcuMapIterator.html',1,'rcu']]],
  ['re2replacement_20',['Re2Replacement',['../d2/d93/structutils_1_1Re2Replacement.html',1,'utils']]],
  ['readablebase_21',['ReadableBase',['../da/d1b/classengine_1_1io_1_1ReadableBase.html',1,'engine::io']]],
  ['readableptr_22',['ReadablePtr',['../dd/df3/classrcu_1_1ReadablePtr.html',1,'rcu']]],
  ['readableptr_3c_20engine_3a_3asubprocess_3a_3aenvironmentvariables_20_3e_23',['ReadablePtr&lt; engine::subprocess::EnvironmentVariables &gt;',['../dd/df3/classrcu_1_1ReadablePtr.html',1,'rcu']]],
  ['readcontext_24',['ReadContext',['../d3/d7d/classproto__structs_1_1io_1_1ReadContext.html',1,'proto_structs::io']]],
  ['reader_25',['Reader',['../d2/d03/classdump_1_1Reader.html',1,'dump::Reader'],['../d4/d6c/classgrpc__proto__structs_1_1client_1_1Reader.html',1,'grpc_proto_structs::client::Reader&lt; StructsResponse &gt;'],['../d0/d74/classgrpc__proto__structs_1_1server_1_1Reader.html',1,'grpc_proto_structs::server::Reader&lt; Request &gt;'],['../d7/d9d/classugrpc_1_1client_1_1Reader.html',1,'ugrpc::client::Reader&lt; Response &gt;'],['../db/dd8/classugrpc_1_1server_1_1Reader.html',1,'ugrpc::server::Reader&lt; Request &gt;']]],
  ['reader_3c_20protobufresponse_20_3e_26',['Reader&lt; ProtobufResponse &gt;',['../d7/d9d/classugrpc_1_1client_1_1Reader.html',1,'ugrpc::client']]],
  ['reader_3c_20requestmessage_20_3e_27',['Reader&lt; RequestMessage &gt;',['../db/dd8/classugrpc_1_1server_1_1Reader.html',1,'ugrpc::server']]],
  ['readerror_28',['ReadError',['../d2/d7f/classproto__structs_1_1ReadError.html',1,'proto_structs']]],
  ['readerwriter_29',['ReaderWriter',['../dd/da4/classgrpc__proto__structs_1_1client_1_1ReaderWriter.html',1,'grpc_proto_structs::client::ReaderWriter&lt; StructsRequest, StructsResponse &gt;'],['../d2/def/classgrpc__proto__structs_1_1server_1_1ReaderWriter.html',1,'grpc_proto_structs::server::ReaderWriter&lt; Request, Response &gt;'],['../d8/d9b/classugrpc_1_1client_1_1ReaderWriter.html',1,'ugrpc::client::ReaderWriter&lt; Request, Response &gt;'],['../dc/db1/classugrpc_1_1server_1_1ReaderWriter.html',1,'ugrpc::server::ReaderWriter&lt; Request, Response &gt;']]],
  ['readerwriter_3c_20grpc_3a_3abytebuffer_2c_20grpc_3a_3abytebuffer_20_3e_30',['ReaderWriter&lt; grpc::ByteBuffer, grpc::ByteBuffer &gt;',['../dc/db1/classugrpc_1_1server_1_1ReaderWriter.html',1,'ugrpc::server']]],
  ['readerwriter_3c_20protobufrequest_2c_20protobufresponse_20_3e_31',['ReaderWriter&lt; ProtobufRequest, ProtobufResponse &gt;',['../d8/d9b/classugrpc_1_1client_1_1ReaderWriter.html',1,'ugrpc::client']]],
  ['readerwriter_3c_20typename_20reader_3c_20request_20_3e_3a_3arequestmessage_2c_20typename_20writer_3c_20response_20_3e_3a_3aresponsemessage_20_3e_32',['ReaderWriter&lt; typename Reader&lt; Request &gt;::RequestMessage, typename Writer&lt; Response &gt;::ResponseMessage &gt;',['../dc/db1/classugrpc_1_1server_1_1ReaderWriter.html',1,'ugrpc::server']]],
  ['readonlystrategy_33',['ReadOnlyStrategy',['../d1/d8c/classstorages_1_1sqlite_1_1infra_1_1strategy_1_1ReadOnlyStrategy.html',1,'storages::sqlite::infra::strategy']]],
  ['readpreference_34',['ReadPreference',['../dc/db5/classstorages_1_1mongo_1_1options_1_1ReadPreference.html',1,'storages::mongo::options']]],
  ['readtableresults_35',['ReadTableResults',['../d4/d81/classydb_1_1ReadTableResults.html',1,'ydb']]],
  ['readwritestrategy_36',['ReadWriteStrategy',['../df/df1/classstorages_1_1sqlite_1_1infra_1_1strategy_1_1ReadWriteStrategy.html',1,'storages::sqlite::infra::strategy']]],
  ['recentperiod_37',['RecentPeriod',['../d2/d67/classutils_1_1statistics_1_1RecentPeriod.html',1,'utils::statistics']]],
  ['recvfromresult_38',['RecvFromResult',['../dc/d72/structengine_1_1io_1_1Socket_1_1RecvFromResult.html',1,'engine::io::Socket']]],
  ['redis_39',['Redis',['../d6/dd0/classcomponents_1_1Redis.html',1,'components']]],
  ['rediscontrol_40',['RedisControl',['../d4/dfe/structtestsuite_1_1RedisControl.html',1,'testsuite']]],
  ['redislocal_41',['RedisLocal',['../df/d18/classstorages_1_1redis_1_1utest_1_1RedisLocal.html',1,'storages::redis::utest']]],
  ['redistest_42',['RedisTest',['../d8/d84/classstorages_1_1redis_1_1utest_1_1RedisTest.html',1,'storages::redis::utest']]],
  ['rediswaitconnected_43',['RedisWaitConnected',['../d5/d66/structstorages_1_1redis_1_1RedisWaitConnected.html',1,'storages::redis']]],
  ['refillpolicy_44',['RefillPolicy',['../de/d15/structutils_1_1TokenBucket_1_1RefillPolicy.html',1,'utils::TokenBucket']]],
  ['reflectionservicecomponent_45',['ReflectionServiceComponent',['../d1/ddc/classgrpc__reflection_1_1ReflectionServiceComponent.html',1,'grpc_reflection']]],
  ['regex_46',['regex',['../dd/d3e/classutils_1_1regex.html',1,'utils']]],
  ['regexerror_47',['RegexError',['../d1/dc0/classutils_1_1RegexError.html',1,'utils']]],
  ['registeredntrx_48',['RegisteredNtrx',['../dc/d90/classpytest__userver_1_1plugins_1_1postgresql_1_1RegisteredNtrx.html',1,'pytest_userver::plugins::postgresql']]],
  ['registeredntrxfailuretype_49',['RegisteredNtrxFailureType',['../d3/dad/classpytest__userver_1_1plugins_1_1postgresql_1_1RegisteredNtrxFailureType.html',1,'pytest_userver::plugins::postgresql']]],
  ['registeredtrx_50',['RegisteredTrx',['../d2/dd0/classpytest__userver_1_1sql_1_1RegisteredTrx.html',1,'pytest_userver::sql']]],
  ['relaxedcounter_51',['RelaxedCounter',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['relaxedcounter_3c_20size_5ft_20_3e_52',['RelaxedCounter&lt; size_t &gt;',['../d9/d48/classutils_1_1statistics_1_1RelaxedCounter.html',1,'utils::statistics']]],
  ['reliablechannel_53',['ReliableChannel',['../db/deb/classurabbitmq_1_1ReliableChannel.html',1,'urabbitmq']]],
  ['removetuplereferences_54',['RemoveTupleReferences',['../d1/d86/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences.html',1,'storages::postgres::io::traits']]],
  ['removetuplereferences_3c_20std_3a_3atuple_3c_20t_2e_2e_2e_20_3e_20_3e_55',['RemoveTupleReferences&lt; std::tuple&lt; T... &gt; &gt;',['../d7/dd1/structstorages_1_1postgres_1_1io_1_1traits_1_1RemoveTupleReferences_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html',1,'storages::postgres::io::traits']]],
  ['repeated_56',['Repeated',['../df/dda/structstructs_1_1Repeated.html',1,'structs']]],
  ['repeatedfield_57',['RepeatedField',['../d3/ddb/classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedmessagedata_58',['RepeatedMessageData',['../d7/d8f/structprotobuf_1_1json_1_1tests_1_1RepeatedMessageData.html',1,'protobuf::json::tests']]],
  ['repeatedptrfield_59',['RepeatedPtrField',['../d6/d36/classgoogle_1_1protobuf_1_1RepeatedPtrField.html',1,'google::protobuf']]],
  ['replaceone_60',['ReplaceOne',['../d4/d75/classstorages_1_1mongo_1_1bulk__ops_1_1ReplaceOne.html',1,'storages::mongo::bulk_ops::ReplaceOne'],['../d5/de4/classstorages_1_1mongo_1_1operations_1_1ReplaceOne.html',1,'storages::mongo::operations::ReplaceOne']]],
  ['replicationmonitoringsettings_61',['ReplicationMonitoringSettings',['../d7/d85/structstorages_1_1redis_1_1ReplicationMonitoringSettings.html',1,'storages::redis']]],
  ['reply_62',['Reply',['../d7/dc1/structdynamic__config_1_1Client_1_1Reply.html',1,'dynamic_config::Client::Reply'],['../d3/d48/classstorages_1_1redis_1_1Reply.html',1,'storages::redis::Reply']]],
  ['replydata_63',['ReplyData',['../da/d08/classstorages_1_1redis_1_1ReplyData.html',1,'storages::redis']]],
  ['replyelemholder_64',['ReplyElemHolder',['../dc/da7/classstorages_1_1redis_1_1ScanRequest_1_1Iterator_1_1ReplyElemHolder.html',1,'storages::redis::ScanRequest::Iterator']]],
  ['request_65',['Request',['../de/df5/classclients_1_1http_1_1Request.html',1,'clients::http::Request'],['../d9/d8d/structs3api_1_1Request.html',1,'s3api::Request'],['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis::Request&lt; ResultType, ReplyType &gt;'],['../da/dc2/classutils_1_1statistics_1_1Request.html',1,'utils::statistics::Request']]],
  ['request_3c_20double_20_3e_66',['Request&lt; double &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20expirereply_20_3e_67',['Request&lt; ExpireReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20hsetreply_20_3e_68',['Request&lt; HsetReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20int64_5ft_20_3e_69',['Request&lt; int64_t &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20keytype_20_3e_70',['Request&lt; KeyType &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20persistreply_20_3e_71',['Request&lt; PersistReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20replydata_20_3e_72',['Request&lt; ReplyData &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20replydata_2c_20void_20_3e_73',['Request&lt; ReplyData, void &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20setreply_20_3e_74',['Request&lt; SetReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20size_5ft_20_3e_75',['Request&lt; size_t &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20size_5ft_2c_20bool_20_3e_76',['Request&lt; size_t, bool &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20statusok_2c_20void_20_3e_77',['Request&lt; StatusOk, void &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20statuspong_2c_20void_20_3e_78',['Request&lt; StatusPong, void &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3achrono_3a_3asystem_5fclock_3a_3atime_5fpoint_20_3e_79',['Request&lt; std::chrono::system_clock::time_point &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aoptional_3c_20double_20_3e_20_3e_80',['Request&lt; std::optional&lt; double &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aoptional_3c_20statusok_20_3e_2c_20bool_20_3e_81',['Request&lt; std::optional&lt; StatusOk &gt;, bool &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aoptional_3c_20std_3a_3astring_20_3e_20_3e_82',['Request&lt; std::optional&lt; std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3astring_20_3e_83',['Request&lt; std::string &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aunordered_5fmap_3c_20std_3a_3astring_2c_20std_3a_3astring_20_3e_20_3e_84',['Request&lt; std::unordered_map&lt; std::string, std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3aunordered_5fset_3c_20std_3a_3astring_20_3e_20_3e_85',['Request&lt; std::unordered_set&lt; std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20geopoint_20_3e_20_3e_86',['Request&lt; std::vector&lt; GeoPoint &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20memberscore_20_3e_20_3e_87',['Request&lt; std::vector&lt; MemberScore &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20std_3a_3aoptional_3c_20point_20_3e_20_3e_20_3e_88',['Request&lt; std::vector&lt; std::optional&lt; Point &gt; &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20std_3a_3aoptional_3c_20std_3a_3astring_20_3e_20_3e_20_3e_89',['Request&lt; std::vector&lt; std::optional&lt; std::string &gt; &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20std_3a_3avector_3c_20std_3a_3astring_20_3e_20_3e_90',['Request&lt; std::vector&lt; std::string &gt; &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['request_3c_20ttlreply_20_3e_91',['Request&lt; TtlReply &gt;',['../dc/d4a/classstorages_1_1redis_1_1Request.html',1,'storages::redis']]],
  ['requestcancelledexception_92',['RequestCancelledException',['../d0/d73/classstorages_1_1redis_1_1RequestCancelledException.html',1,'storages::redis']]],
  ['requestcontext_93',['RequestContext',['../de/df6/classserver_1_1request_1_1RequestContext.html',1,'server::request']]],
  ['requestdatabase_94',['RequestDataBase',['../d4/ddc/classstorages_1_1redis_1_1RequestDataBase.html',1,'storages::redis']]],
  ['requesterror_95',['RequestError',['../d2/d06/classgrpc__protovalidate_1_1client_1_1RequestError.html',1,'grpc_protovalidate::client']]],
  ['requesteval_96',['RequestEval',['../df/d69/classstorages_1_1redis_1_1RequestEval.html',1,'storages::redis']]],
  ['requestevalsha_97',['RequestEvalSha',['../d5/daf/classstorages_1_1redis_1_1RequestEvalSha.html',1,'storages::redis']]],
  ['requestfailedexception_98',['RequestFailedException',['../d0/d0c/classstorages_1_1redis_1_1RequestFailedException.html',1,'storages::redis']]],
  ['requestgeneric_99',['RequestGeneric',['../df/d89/classstorages_1_1redis_1_1RequestGeneric.html',1,'storages::redis']]],
  ['requestinfo_100',['RequestInfo',['../d1/da9/structugrpc_1_1RequestInfo.html',1,'ugrpc']]],
  ['requestparseerror_101',['RequestParseError',['../d4/ddf/classserver_1_1handlers_1_1RequestParseError.html',1,'server::handlers']]],
  ['requestscandata_102',['RequestScanData',['../d7/dbd/classstorages_1_1redis_1_1RequestScanData.html',1,'storages::redis']]],
  ['requestscandatabase_103',['RequestScanDataBase',['../da/d20/classstorages_1_1redis_1_1RequestScanDataBase.html',1,'storages::redis']]],
  ['requestssource_104',['RequestsSource',['../d1/dc2/classserver_1_1congestion__control_1_1RequestsSource.html',1,'server::congestion_control']]],
  ['requesttraits_105',['RequestTraits',['../d7/d18/structutils_1_1hedging_1_1RequestTraits.html',1,'utils::hedging']]],
  ['resolver_106',['Resolver',['../d0/d75/classclients_1_1dns_1_1Resolver.html',1,'clients::dns']]],
  ['resolverexception_107',['ResolverException',['../d8/d54/classclients_1_1dns_1_1ResolverException.html',1,'clients::dns']]],
  ['resourceexhaustederror_108',['ResourceExhaustedError',['../d8/db2/classugrpc_1_1client_1_1ResourceExhaustedError.html',1,'ugrpc::client']]],
  ['resourceinfo_109',['ResourceInfo',['../d3/d30/structugrpc_1_1ResourceInfo.html',1,'ugrpc']]],
  ['resourcenotfound_110',['ResourceNotFound',['../d2/d91/classserver_1_1handlers_1_1ResourceNotFound.html',1,'server::handlers']]],
  ['response_111',['Response',['../dd/d3b/classclients_1_1http_1_1Response.html',1,'clients::http::Response'],['../d8/d24/structutest_1_1SimpleServer_1_1Response.html',1,'utest::SimpleServer::Response']]],
  ['responsebase_112',['ResponseBase',['../d3/dee/classserver_1_1request_1_1ResponseBase.html',1,'server::request']]],
  ['responsebodystream_113',['ResponseBodyStream',['../dd/d63/classserver_1_1http_1_1ResponseBodyStream.html',1,'server::http']]],
  ['responsedataaccounter_114',['ResponseDataAccounter',['../d0/d6f/classserver_1_1request_1_1ResponseDataAccounter.html',1,'server::request']]],
  ['responseerror_115',['ResponseError',['../d6/db8/classgrpc__protovalidate_1_1client_1_1ResponseError.html',1,'grpc_protovalidate::client']]],
  ['responsefuture_116',['ResponseFuture',['../d0/d9b/classclients_1_1http_1_1ResponseFuture.html',1,'clients::http::ResponseFuture'],['../df/dbd/classgrpc__proto__structs_1_1client_1_1ResponseFuture.html',1,'grpc_proto_structs::client::ResponseFuture&lt; Response &gt;'],['../d6/d3b/classugrpc_1_1client_1_1ResponseFuture.html',1,'ugrpc::client::ResponseFuture&lt; Response &gt;']]],
  ['responsefuture_3c_20vanillaresponse_20_3e_117',['ResponseFuture&lt; VanillaResponse &gt;',['../d6/d3b/classugrpc_1_1client_1_1ResponseFuture.html',1,'ugrpc::client']]],
  ['responseparsingerror_118',['ResponseParsingError',['../d2/dd7/classs3api_1_1ResponseParsingError.html',1,'s3api']]],
  ['responsetruncatederror_119',['ResponseTruncatedError',['../db/dcc/classydb_1_1ResponseTruncatedError.html',1,'ydb']]],
  ['restart_120',['Restart',['../dc/d53/classserver_1_1handlers_1_1Restart.html',1,'server::handlers']]],
  ['restrictviolation_121',['RestrictViolation',['../d9/daa/classstorages_1_1postgres_1_1RestrictViolation.html',1,'storages::postgres']]],
  ['result_122',['Result',['../d9/d97/classugrpc_1_1server_1_1Result.html',1,'ugrpc::server']]],
  ['resultset_123',['ResultSet',['../d0/d5b/classstorages_1_1postgres_1_1ResultSet.html',1,'storages::postgres::ResultSet'],['../dc/da3/classstorages_1_1sqlite_1_1ResultSet.html',1,'storages::sqlite::ResultSet']]],
  ['resultseterror_124',['ResultSetError',['../d5/d9d/classstorages_1_1postgres_1_1ResultSetError.html',1,'storages::postgres']]],
  ['resultstore_125',['ResultStore',['../d9/d54/classutils_1_1ResultStore.html',1,'utils']]],
  ['resultstore_3c_20void_20_3e_126',['ResultStore&lt; void &gt;',['../dc/db9/classutils_1_1ResultStore_3_01void_01_4.html',1,'utils']]],
  ['retrybudget_127',['RetryBudget',['../d5/d9f/classutils_1_1RetryBudget.html',1,'utils']]],
  ['retrybudgetsettings_128',['RetryBudgetSettings',['../d4/df0/structutils_1_1RetryBudgetSettings.html',1,'utils']]],
  ['retryconfig_129',['RetryConfig',['../d3/daa/structugrpc_1_1client_1_1RetryConfig.html',1,'ugrpc::client']]],
  ['retryduplicatekey_130',['RetryDuplicateKey',['../d8/d28/classstorages_1_1mongo_1_1options_1_1RetryDuplicateKey.html',1,'storages::mongo::options']]],
  ['retryinfo_131',['RetryInfo',['../dc/d8d/structugrpc_1_1RetryInfo.html',1,'ugrpc']]],
  ['retrynilfrommaster_132',['RetryNilFromMaster',['../d9/d6d/structstorages_1_1redis_1_1RetryNilFromMaster.html',1,'storages::redis']]],
  ['returnnew_133',['ReturnNew',['../df/d9c/classstorages_1_1mongo_1_1options_1_1ReturnNew.html',1,'storages::mongo::options']]],
  ['reverseconstfielditerator_134',['ReverseConstFieldIterator',['../d1/d69/classstorages_1_1postgres_1_1ReverseConstFieldIterator.html',1,'storages::postgres']]],
  ['reverseconstrowiterator_135',['ReverseConstRowIterator',['../d6/d82/classstorages_1_1postgres_1_1ReverseConstRowIterator.html',1,'storages::postgres']]],
  ['richstatus_136',['RichStatus',['../db/d70/classugrpc_1_1RichStatus.html',1,'ugrpc']]],
  ['rounddownroundpolicy_137',['RoundDownRoundPolicy',['../dd/d4c/classdecimal64_1_1RoundDownRoundPolicy.html',1,'decimal64']]],
  ['rounduproundpolicy_138',['RoundUpRoundPolicy',['../de/dc3/classdecimal64_1_1RoundUpRoundPolicy.html',1,'decimal64']]],
  ['row_139',['Row',['../db/dfe/classstorages_1_1postgres_1_1Row.html',1,'storages::postgres::Row'],['../dc/db6/classydb_1_1Row.html',1,'ydb::Row']]],
  ['rowcategory_140',['RowCategory',['../d3/d4b/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory.html',1,'storages::postgres::io::traits']]],
  ['rowcategory_3c_3a_3autils_3a_3astrongtypedef_3c_20tag_2c_20t_2c_20ops_2c_20enable_20_3e_20_3e_141',['RowCategory&lt;::utils::StrongTypedef&lt; Tag, T, Ops, Enable &gt; &gt;',['../da/d9a/structstorages_1_1postgres_1_1io_1_1traits_1_1RowCategory_3_1_1utils_1_1StrongTypedef_3_01Tag_00a475f9e72ca0f19000d262961377c32b.html',1,'storages::postgres::io::traits']]],
  ['rowdescription_142',['RowDescription',['../d1/d9f/classstorages_1_1postgres_1_1RowDescription.html',1,'storages::postgres']]],
  ['rowindexoutofbounds_143',['RowIndexOutOfBounds',['../db/dea/classstorages_1_1postgres_1_1RowIndexOutOfBounds.html',1,'storages::postgres']]],
  ['rowsmapper_144',['RowsMapper',['../d8/d1d/classstorages_1_1clickhouse_1_1io_1_1RowsMapper.html',1,'storages::clickhouse::io']]],
  ['rowtag_145',['RowTag',['../d6/d4d/structstorages_1_1mysql_1_1RowTag.html',1,'storages::mysql::RowTag'],['../df/d46/structstorages_1_1postgres_1_1RowTag.html',1,'storages::postgres::RowTag'],['../df/d2b/structstorages_1_1sqlite_1_1RowTag.html',1,'storages::sqlite::RowTag']]],
  ['rowtype_146',['RowType',['../d4/dce/structstorages_1_1postgres_1_1io_1_1RowType.html',1,'storages::postgres::io']]],
  ['rpccancellederror_147',['RpcCancelledError',['../d8/ddb/classugrpc_1_1client_1_1RpcCancelledError.html',1,'ugrpc::client']]],
  ['rpcerror_148',['RpcError',['../d3/d28/classugrpc_1_1client_1_1RpcError.html',1,'ugrpc::client::RpcError'],['../db/d1c/classugrpc_1_1server_1_1RpcError.html',1,'ugrpc::server::RpcError']]],
  ['rpcinterruptederror_149',['RpcInterruptedError',['../db/d86/classugrpc_1_1client_1_1RpcInterruptedError.html',1,'ugrpc::client::RpcInterruptedError'],['../d0/dd9/classugrpc_1_1server_1_1RpcInterruptedError.html',1,'ugrpc::server::RpcInterruptedError']]],
  ['runnercomponentbase_150',['RunnerComponentBase',['../d7/dd1/classmiddlewares_1_1RunnerComponentBase.html',1,'middlewares']]],
  ['runnercomponentbase_3c_20middlewarebase_2c_20clientinfo_20_3e_151',['RunnerComponentBase&lt; MiddlewareBase, ClientInfo &gt;',['../d7/dd1/classmiddlewares_1_1RunnerComponentBase.html',1,'middlewares']]],
  ['runnercomponentbase_3c_20middlewarebase_2c_20serviceinfo_20_3e_152',['RunnerComponentBase&lt; MiddlewareBase, ServiceInfo &gt;',['../d7/dd1/classmiddlewares_1_1RunnerComponentBase.html',1,'middlewares']]],
  ['runtimeerror_153',['RuntimeError',['../d6/d97/classstorages_1_1postgres_1_1RuntimeError.html',1,'storages::postgres']]],
  ['rwbase_154',['RwBase',['../d3/d1e/classengine_1_1io_1_1RwBase.html',1,'engine::io']]]
];
