var searchData=
[
  ['s_20own_20samples_20tests_20and_20benchmarks_0',['Build instructions for userver&apos;s own samples, tests and benchmarks',['../df/d35/md_en_2userver_2build_2userver.html',1,'']]],
  ['s3_20api_1',['S3 API',['../da/dc5/md_en_2userver_2libraries_2s3api.html',1,'']]],
  ['s3_20client_20tutorial_2',['S3 client tutorial',['../d3/d34/md_en_2userver_2tutorial_2s3api.html',1,'']]],
  ['samples_20tests_20and_20benchmarks_3',['Build instructions for userver&apos;s own samples, tests and benchmarks',['../df/d35/md_en_2userver_2build_2userver.html',1,'']]],
  ['schema_20codegen_20the_20chaotic_4',['JSON schema codegen - the Chaotic',['../d8/d43/md_en_2userver_2chaotic.html',1,'']]],
  ['schemas_20list_5',['Dynamic config schemas list',['../db/d70/md_en_2dynamic__configs_2dynamic__configs.html',1,'']]],
  ['security_20changelog_6',['Security Changelog',['../db/dde/md_en_2userver_2security__changelog.html',1,'']]],
  ['security_20policy_7',['Security Policy',['../de/d1b/md__2data_2code_2userver_2SECURITY.html',1,'']]],
  ['server_8',['server',['../da/d16/md_en_2userver_2tutorial_2hello__service.html',1,'Writing your first HTTP server'],['../d4/d95/md_en_2userver_2tutorial_2config__service.html',1,'Writing your own configs server']]],
  ['server_20middleware_20implementation_9',['gRPC server middleware implementation',['../d7/d4b/md_en_2userver_2grpc_2server__middleware__implementation.html',1,'']]],
  ['server_20middlewares_10',['server middlewares',['../da/de9/md_en_2userver_2grpc_2server__middlewares.html',1,'gRPC server middlewares'],['../d6/dcc/md_en_2userver_2http__server__middlewares.html',1,'Http server middlewares']]],
  ['server_20with_20metrics_20and_20spans_11',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['server_20with_20static_20configs_20validation_12',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['server_5fcomponent_13',['server_component',['../de/ddb/md_en_2components__schema_2grpc_2src_2ugrpc_2server_2server__component.html',1,'']]],
  ['server_5fmonitor_14',['server_monitor',['../d5/d7b/md_en_2components__schema_2core_2src_2server_2handlers_2server__monitor.html',1,'']]],
  ['service_15',['service',['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html',1,'gRPC client and service'],['../d9/d1c/md_en_2userver_2tutorial_2kafka__service.html',1,'Kafka service'],['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'Memory profiling a production service'],['../d5/d81/md_en_2userver_2tutorial_2mongo__service.html',1,'MongoDB service'],['../d4/d31/md_en_2userver_2tutorial_2postgres__service.html',1,'PostgreSQL service'],['../d3/da2/md_en_2userver_2tutorial_2redis__service.html',1,'Valkey/Redis service'],['../d7/d9e/md_en_2userver_2tutorial_2websocket__service.html',1,'Writing your WebSocket service']]],
  ['service_20statistics_20and_20metrics_20prometheus_20graphite_20and_20default_20metrics_20description_16',['Retrieveing Service Statistics and Metrics (Prometheus/Graphite/...) and Default Metrics Description',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['service_20tests_20testsuite_17',['Functional service tests (testsuite)',['../df/d07/md_en_2userver_2functional__testing.html',1,'']]],
  ['service_5fcomponent_5fbase_18',['service_component_base',['../d5/da8/md_en_2components__schema_2grpc_2src_2ugrpc_2server_2service__component__base.html',1,'']]],
  ['serving_20static_20content_20and_20dynamic_20web_20pages_19',['Serving Static Content and Dynamic Web Pages',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html',1,'']]],
  ['sets_20',['uPg: Working with result sets',['../db/db5/pg_process_results.html',1,'']]],
  ['signals_21',['Handling OS signals',['../df/d4e/md_en_2userver_2os__signals.html',1,'']]],
  ['simple_5fclient_5fcomponent_22',['simple_client_component',['../dc/db2/md_en_2components__schema_2grpc_2src_2ugrpc_2client_2simple__client__component.html',1,'']]],
  ['single_20file_20prototyping_23',['Easy - library for single file prototyping',['../da/de8/md_en_2userver_2libraries_2easy.html',1,'']]],
  ['single_5fthreaded_5ftask_5fprocessors_24',['single_threaded_task_processors',['../d8/d2e/md_en_2components__schema_2core_2src_2components_2single__threaded__task__processors.html',1,'']]],
  ['spans_25',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['specific_20configurations_26',['Deploy Environment Specific Configurations',['../d2/d58/md_en_2userver_2deploy__env.html',1,'']]],
  ['sql_20yql_20files_20via_20userver_5fadd_5fsql_5flibrary_27',['Embedding SQL/YQL files via userver_add_sql_library',['../d6/de0/md_en_2userver_2sql__files.html',1,'']]],
  ['sqlite_20driver_28',['SQLite Driver',['../dd/d8a/md_en_2userver_2sqlite_2sqlite__driver.html',1,'']]],
  ['sqlite_20driver_20design_20and_20implementation_20details_29',['SQLite driver design and implementation details',['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html',1,'']]],
  ['sqlite_20supported_20types_30',['SQLite supported types',['../d3/d68/md_en_2userver_2sqlite_2supported__types.html',1,'']]],
  ['stability_20versioning_31',['API and ABI stability, versioning',['../db/d57/md_en_2userver_2development_2stability.html',1,'']]],
  ['stack_32',['Coroutine stack',['../d7/dc8/md_en_2userver_2stack.html',1,'']]],
  ['static_20configs_20validation_33',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['static_20content_20and_20dynamic_20web_20pages_34',['Serving Static Content and Dynamic Web Pages',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html',1,'']]],
  ['statistics_20and_20metrics_35',['Statistics and Metrics',['../d1/d9a/md_en_2userver_2metrics.html',1,'']]],
  ['statistics_20and_20metrics_20prometheus_20graphite_20and_20default_20metrics_20description_36',['Retrieveing Service Statistics and Metrics (Prometheus/Graphite/...) and Default Metrics Description',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['statistics_5fstorage_37',['statistics_storage',['../dd/d34/md_en_2components__schema_2core_2src_2components_2statistics__storage.html',1,'']]],
  ['strong_20typedef_20idiom_38',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../d3/ddf/pg_strong_typedef.html',1,'']]],
  ['support_20for_20c_20strong_20typedef_20idiom_39',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../d3/ddf/pg_strong_typedef.html',1,'']]],
  ['supported_20data_20types_40',['uPg: Supported data types',['../dd/dad/md_en_2userver_2pg__types.html',1,'']]],
  ['supported_20platforms_41',['Supported Platforms',['../d0/dd5/md_en_2userver_2supported__platforms.html',1,'']]],
  ['supported_20types_42',['supported types',['../d2/d0a/md_en_2userver_2mysql_2supported__types.html',1,'MySQL supported types'],['../d3/d68/md_en_2userver_2sqlite_2supported__types.html',1,'SQLite supported types']]],
  ['switches_43',['Profiling context switches',['../db/d8f/md_en_2userver_2profile__context__switches.html',1,'']]],
  ['synchronization_20primitives_44',['Synchronization Primitives',['../d6/d6c/md_en_2userver_2synchronization.html',1,'']]],
  ['system_45',['Component system',['../dc/dcc/md_en_2userver_2component__system.html',1,'']]],
  ['system_5fstatistics_5fcollector_46',['system_statistics_collector',['../d1/d21/md_en_2components__schema_2core_2src_2utils_2statistics_2system__statistics__collector.html',1,'']]]
];
