var searchData=
[
  ['ubuntu_2022_2004_0',['ubuntu-22.04',['../de/d9c/md_en_2deps_2ubuntu-22_804.html',1,'']]],
  ['ubuntu_2024_2004_1',['ubuntu-24.04',['../d5/d6a/md_en_2deps_2ubuntu-24_804.html',1,'']]],
  ['uclickhouse_3a_20c_20clickhouse_20mappings_2',['uClickHouse: C++ &lt;-&gt; ClickHouse mappings',['../d8/dfe/md_en_2userver_2clickhouse_2io.html',1,'']]],
  ['unit_20tests_20and_20benchmarks_3',['Unit Tests and Benchmarks',['../d4/d70/md_en_2userver_2testing.html',1,'']]],
  ['upg_20driver_4',['uPg Driver',['../d7/dc1/md_en_2userver_2pg_2driver.html',1,'']]],
  ['upg_3a_20automatic_20connection_20limit_5',['uPg: Automatic connection limit',['../d3/db7/md_en_2userver_2pg_2connlimit__mode__auto.html',1,'']]],
  ['upg_3a_20cluster_20topology_20discovery_6',['uPg: Cluster topology discovery',['../da/d6d/md_en_2userver_2pg_2topology.html',1,'']]],
  ['upg_3a_20postgres_20errors_7',['uPg: Postgres errors',['../d3/d00/md_en_2userver_2pg_2errors.html',1,'']]],
  ['upg_3a_20postgresql_20user_20type_20mappings_8',['uPg: PostgreSQL user type mappings',['../d5/da0/md_en_2userver_2pg_2user__types.html',1,'']]],
  ['upg_3a_20running_20queries_9',['uPg: Running queries',['../d1/d02/md_en_2userver_2pg_2run__queries.html',1,'']]],
  ['upg_3a_20support_20for_20c_20strong_20typedef_20idiom_10',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../db/d7c/md_en_2userver_2pg_2strong__typedef.html',1,'']]],
  ['upg_3a_20supported_20data_20types_11',['uPg: Supported data types',['../d7/dc4/md_en_2userver_2pg_2types.html',1,'']]],
  ['upg_3a_20transactions_12',['uPg: Transactions',['../d5/dac/md_en_2userver_2pg_2transactions.html',1,'']]],
  ['upg_3a_20typed_20postgresql_20results_13',['uPg: Typed PostgreSQL results',['../d5/d53/md_en_2userver_2pg_2user__row__types.html',1,'']]],
  ['upg_3a_20working_20with_20result_20sets_14',['uPg: Working with result sets',['../d0/d72/md_en_2userver_2pg_2process__results.html',1,'']]],
  ['uploads_20and_20multipart_20form_20data_20testing_15',['File uploads and multipart/form-data testing',['../df/d0f/md_en_2userver_2tutorial_2multipart__service.html',1,'']]],
  ['usage_16',['Guide on TaskProcessor Usage',['../db/d90/md_en_2userver_2task__processors__guide.html',1,'']]],
  ['used_20lru_20caches_20and_20expirable_20lru_20caches_17',['Least Recently Used (LRU) Caches and expirable LRU caches',['../d0/dd8/md_en_2userver_2lru__cache.html',1,'']]],
  ['user_20type_20mappings_18',['uPg: PostgreSQL user type mappings',['../d5/da0/md_en_2userver_2pg_2user__types.html',1,'']]],
  ['userver_19',['userver',['../index.html',1,'']]],
  ['userver_20s_20own_20samples_20tests_20and_20benchmarks_20',['Build instructions for userver&apos;s own samples, tests and benchmarks',['../df/d35/md_en_2userver_2build_2userver.html',1,'']]],
  ['userver_5fadd_5fsql_5flibrary_21',['Embedding SQL/YQL files via userver_add_sql_library',['../d6/de0/md_en_2userver_2sql__files.html',1,'']]],
  ['userver_5fbaggage_5fenabled_22',['USERVER_BAGGAGE_ENABLED',['../d7/dd9/md_en_2dynamic__configs_2USERVER__BAGGAGE__ENABLED.html',1,'']]],
  ['userver_5fcaches_23',['USERVER_CACHES',['../d6/d3e/md_en_2dynamic__configs_2USERVER__CACHES.html',1,'']]],
  ['userver_5fcancel_5fhandle_5frequest_5fby_5fdeadline_24',['USERVER_CANCEL_HANDLE_REQUEST_BY_DEADLINE',['../d0/d9d/md_en_2dynamic__configs_2USERVER__CANCEL__HANDLE__REQUEST__BY__DEADLINE.html',1,'']]],
  ['userver_5fdeadline_5fpropagation_5fabsolute_5ftimestamp_5fenabled_25',['USERVER_DEADLINE_PROPAGATION_ABSOLUTE_TIMESTAMP_ENABLED',['../d9/d1f/md_en_2dynamic__configs_2USERVER__DEADLINE__PROPAGATION__ABSOLUTE__TIMESTAMP__ENABLED.html',1,'']]],
  ['userver_5fdeadline_5fpropagation_5fclock_5fskew_5fthreshold_5fms_26',['USERVER_DEADLINE_PROPAGATION_CLOCK_SKEW_THRESHOLD_MS',['../d4/d79/md_en_2dynamic__configs_2USERVER__DEADLINE__PROPAGATION__CLOCK__SKEW__THRESHOLD__MS.html',1,'']]],
  ['userver_5fdeadline_5fpropagation_5fenabled_27',['USERVER_DEADLINE_PROPAGATION_ENABLED',['../dc/da0/md_en_2dynamic__configs_2USERVER__DEADLINE__PROPAGATION__ENABLED.html',1,'']]],
  ['userver_5fdumps_28',['USERVER_DUMPS',['../d4/d89/md_en_2dynamic__configs_2USERVER__DUMPS.html',1,'']]],
  ['userver_5ffiles_5fcontent_5ftype_5fmap_29',['USERVER_FILES_CONTENT_TYPE_MAP',['../d2/d59/md_en_2dynamic__configs_2USERVER__FILES__CONTENT__TYPE__MAP.html',1,'']]],
  ['userver_5fgrpc_5fclient_5fenable_5fdeadline_5fpropagation_30',['USERVER_GRPC_CLIENT_ENABLE_DEADLINE_PROPAGATION',['../d7/d9e/md_en_2dynamic__configs_2USERVER__GRPC__CLIENT__ENABLE__DEADLINE__PROPAGATION.html',1,'']]],
  ['userver_5fgrpc_5fserver_5fcancel_5ftask_5fby_5fdeadline_31',['USERVER_GRPC_SERVER_CANCEL_TASK_BY_DEADLINE',['../d4/d84/md_en_2dynamic__configs_2USERVER__GRPC__SERVER__CANCEL__TASK__BY__DEADLINE.html',1,'']]],
  ['userver_5fhttp_5fproxy_32',['USERVER_HTTP_PROXY',['../d5/dc8/md_en_2dynamic__configs_2USERVER__HTTP__PROXY.html',1,'']]],
  ['userver_5flog_5fdynamic_5fdebug_33',['USERVER_LOG_DYNAMIC_DEBUG',['../d1/d57/md_en_2dynamic__configs_2USERVER__LOG__DYNAMIC__DEBUG.html',1,'']]],
  ['userver_5flog_5frequest_34',['USERVER_LOG_REQUEST',['../db/dd7/md_en_2dynamic__configs_2USERVER__LOG__REQUEST.html',1,'']]],
  ['userver_5flog_5frequest_5fheaders_35',['USERVER_LOG_REQUEST_HEADERS',['../de/d23/md_en_2dynamic__configs_2USERVER__LOG__REQUEST__HEADERS.html',1,'']]],
  ['userver_5flog_5frequest_5fheaders_5fwhitelist_36',['USERVER_LOG_REQUEST_HEADERS_WHITELIST',['../de/d72/md_en_2dynamic__configs_2USERVER__LOG__REQUEST__HEADERS__WHITELIST.html',1,'']]],
  ['userver_5flru_5fcaches_37',['USERVER_LRU_CACHES',['../d5/d7a/md_en_2dynamic__configs_2USERVER__LRU__CACHES.html',1,'']]],
  ['userver_5fno_5flog_5fspans_38',['USERVER_NO_LOG_SPANS',['../d7/db4/md_en_2dynamic__configs_2USERVER__NO__LOG__SPANS.html',1,'']]],
  ['userver_5fodbc_5fconnection_5fpool_5fsettings_39',['USERVER_ODBC_CONNECTION_POOL_SETTINGS',['../d4/db7/md_en_2dynamic__configs_2USERVER__ODBC__CONNECTION__POOL__SETTINGS.html',1,'']]],
  ['userver_5fodbc_5fdefault_5fcommand_5fcontrol_40',['USERVER_ODBC_DEFAULT_COMMAND_CONTROL',['../d5/da0/md_en_2dynamic__configs_2USERVER__ODBC__DEFAULT__COMMAND__CONTROL.html',1,'']]],
  ['userver_5frps_5fccontrol_41',['USERVER_RPS_CCONTROL',['../d1/d1b/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL.html',1,'']]],
  ['userver_5frps_5fccontrol_5factivated_5ffactor_5fmetric_42',['USERVER_RPS_CCONTROL_ACTIVATED_FACTOR_METRIC',['../da/d38/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL__ACTIVATED__FACTOR__METRIC.html',1,'']]],
  ['userver_5frps_5fccontrol_5fcustom_5fstatus_43',['USERVER_RPS_CCONTROL_CUSTOM_STATUS',['../d8/da3/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL__CUSTOM__STATUS.html',1,'']]],
  ['userver_5frps_5fccontrol_5fenabled_44',['USERVER_RPS_CCONTROL_ENABLED',['../d4/d4e/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL__ENABLED.html',1,'']]],
  ['userver_5ftask_5fprocessor_5fprofiler_5fdebug_45',['USERVER_TASK_PROCESSOR_PROFILER_DEBUG',['../d9/d43/md_en_2dynamic__configs_2USERVER__TASK__PROCESSOR__PROFILER__DEBUG.html',1,'']]],
  ['userver_5ftask_5fprocessor_5fqos_46',['USERVER_TASK_PROCESSOR_QOS',['../d4/dc7/md_en_2dynamic__configs_2USERVER__TASK__PROCESSOR__QOS.html',1,'']]]
];
