var searchData=
[
  ['rabbitmq_20amqp_200_209_201_0',['RabbitMQ (AMQP 0-9-1)',['../d7/d90/md_en_2userver_2rabbitmq__driver.html',1,'']]],
  ['recently_20used_20lru_20caches_20and_20expirable_20lru_20caches_1',['Least Recently Used (LRU) Caches and expirable LRU caches',['../d0/dd8/md_en_2userver_2lru__cache.html',1,'']]],
  ['redis_2',['Valkey/Redis',['../dd/dde/md_en_2userver_2redis.html',1,'']]],
  ['redis_20service_3',['Valkey/Redis service',['../d3/da2/md_en_2userver_2tutorial_2redis__service.html',1,'']]],
  ['redis_5fcommands_5fbuffering_5fsettings_4',['REDIS_COMMANDS_BUFFERING_SETTINGS',['../d2/d11/md_en_2dynamic__configs_2REDIS__COMMANDS__BUFFERING__SETTINGS.html',1,'']]],
  ['redis_5fdeadline_5fpropagation_5fversion_5',['REDIS_DEADLINE_PROPAGATION_VERSION',['../d8/d51/md_en_2dynamic__configs_2REDIS__DEADLINE__PROPAGATION__VERSION.html',1,'']]],
  ['redis_5fdefault_5fcommand_5fcontrol_6',['REDIS_DEFAULT_COMMAND_CONTROL',['../d3/db2/md_en_2dynamic__configs_2REDIS__DEFAULT__COMMAND__CONTROL.html',1,'']]],
  ['redis_5fmetrics_5fsettings_7',['REDIS_METRICS_SETTINGS',['../d6/d0e/md_en_2dynamic__configs_2REDIS__METRICS__SETTINGS.html',1,'']]],
  ['redis_5fpubsub_5fmetrics_5fsettings_8',['REDIS_PUBSUB_METRICS_SETTINGS',['../d5/d11/md_en_2dynamic__configs_2REDIS__PUBSUB__METRICS__SETTINGS.html',1,'']]],
  ['redis_5freplica_5fmonitoring_5fsettings_9',['REDIS_REPLICA_MONITORING_SETTINGS',['../d4/d94/md_en_2dynamic__configs_2REDIS__REPLICA__MONITORING__SETTINGS.html',1,'']]],
  ['redis_5fretry_5fbudget_5fsettings_10',['REDIS_RETRY_BUDGET_SETTINGS',['../d2/d76/md_en_2dynamic__configs_2REDIS__RETRY__BUDGET__SETTINGS.html',1,'']]],
  ['redis_5fsubscriber_5fdefault_5fcommand_5fcontrol_11',['REDIS_SUBSCRIBER_DEFAULT_COMMAND_CONTROL',['../d9/d09/md_en_2dynamic__configs_2REDIS__SUBSCRIBER__DEFAULT__COMMAND__CONTROL.html',1,'']]],
  ['redis_5fsubscriptions_5frebalance_5fmin_5finterval_5fseconds_12',['REDIS_SUBSCRIPTIONS_REBALANCE_MIN_INTERVAL_SECONDS',['../d7/d21/md_en_2dynamic__configs_2REDIS__SUBSCRIPTIONS__REBALANCE__MIN__INTERVAL__SECONDS.html',1,'']]],
  ['redis_5fwait_5fconnected_13',['REDIS_WAIT_CONNECTED',['../dd/d28/md_en_2dynamic__configs_2REDIS__WAIT__CONNECTED.html',1,'']]],
  ['reflection_14',['gRPC reflection',['../d9/d39/md_en_2userver_2libraries_2grpc-reflection.html',1,'']]],
  ['releases_20trunk_20based_20development_20and_20pull_20requests_15',['Releases, Trunk-based Development and Pull Requests',['../d0/d7b/md_en_2userver_2development_2releases.html',1,'']]],
  ['remote_16',['Pre-caching data from HTTP remote',['../dc/d8a/md_en_2userver_2tutorial_2http__caching.html',1,'']]],
  ['requests_17',['Releases, Trunk-based Development and Pull Requests',['../d0/d7b/md_en_2userver_2development_2releases.html',1,'']]],
  ['requests_18',['requests',['../d8/d91/md_en_2userver_2tutorial_2flatbuf__service.html',1,'HTTP Flatbuf handler and requests'],['../d8/d7b/md_en_2userver_2requests__in__flight.html',1,'Inspecting in-flight requests']]],
  ['result_20sets_19',['uPg: Working with result sets',['../d0/d72/md_en_2userver_2pg_2process__results.html',1,'']]],
  ['results_20',['uPg: Typed PostgreSQL results',['../d5/d53/md_en_2userver_2pg_2user__row__types.html',1,'']]],
  ['retries_21',['gRPC Timeouts and Retries',['../d8/d54/md_en_2userver_2grpc_2timeouts__retries.html',1,'']]],
  ['retrieving_20service_20statistics_20and_20metrics_20prometheus_20graphite_20and_20default_20metrics_20description_22',['Retrieving Service Statistics and Metrics (Prometheus/Graphite/...) and Default Metrics Description',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['richstatus_23',['RichStatus',['../d3/d21/md_en_2userver_2grpc_2rich__status.html',1,'']]],
  ['roadmap_20and_20changelog_24',['Roadmap and Changelog',['../da/d9a/md_en_2userver_2roadmap__and__changelog.html',1,'']]],
  ['roadmap_20and_20changelog_20v1_20and_20earlier_25',['Roadmap and Changelog (v1 and earlier)',['../dd/d6f/md_en_2userver_2roadmap__and__changelog__v1.html',1,'']]],
  ['runner_5fcomponent_5fbase_26',['runner_component_base',['../de/d93/md_en_2components__schema_2core_2src_2middlewares_2runner__component__base.html',1,'']]],
  ['running_20queries_27',['uPg: Running queries',['../d1/d02/md_en_2userver_2pg_2run__queries.html',1,'']]],
  ['runtime_28',['runtime',['../d7/d5b/md_en_2userver_2dump__coroutines.html',1,'Dump coroutines in runtime'],['../d1/de2/md_en_2userver_2log__level__running__service.html',1,'Logging at runtime']]]
];
