var searchData=
[
  ['data_20from_20http_20remote_0',['Pre-caching data from HTTP remote',['../dc/d8a/md_en_2userver_2tutorial_2http__caching.html',1,'']]],
  ['data_20testing_1',['File uploads and multipart/form-data testing',['../df/d0f/md_en_2userver_2tutorial_2multipart__service.html',1,'']]],
  ['data_20types_2',['uPg: Supported data types',['../dd/dad/md_en_2userver_2pg__types.html',1,'']]],
  ['deadline_20propagation_3',['Deadline propagation',['../d6/d64/md_en_2userver_2deadline__propagation.html',1,'']]],
  ['debian_2012_4',['debian-12',['../d1/dea/md_en_2deps_2debian-12.html',1,'']]],
  ['debian_2013_5',['debian-13',['../d5/d1e/md_en_2deps_2debian-13.html',1,'']]],
  ['debugging_20with_20gdb_6',['Debugging with GDB',['../d2/d1b/md_en_2userver_2gdb__debugging.html',1,'']]],
  ['dependencies_7',['Build dependencies',['../de/db9/md_en_2userver_2build_2dependencies.html',1,'']]],
  ['deploy_20environment_20specific_20configurations_8',['Deploy Environment Specific Configurations',['../d2/d58/md_en_2userver_2deploy__env.html',1,'']]],
  ['deprecated_20list_9',['Deprecated List',['../da/d58/deprecated.html',1,'']]],
  ['design_20and_20implementation_20details_10',['design and implementation details',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html',1,'MySQL driver design and implementation details'],['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html',1,'SQLite driver design and implementation details']]],
  ['details_11',['details',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html',1,'MySQL driver design and implementation details'],['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html',1,'SQLite driver design and implementation details']]],
  ['detection_12',['Long Transactions Detection',['../de/d06/md_en_2userver_2long__transactions.html',1,'']]],
  ['development_20and_20pull_20requests_13',['Releases, Trunk-based Development and Pull Requests',['../d0/d7b/md_en_2userver_2development_2releases.html',1,'']]],
  ['digest_20authorization_20authentication_20via_20postgresql_14',['Digest Authorization/Authentication via PostgreSQL',['../d6/d31/md_en_2userver_2tutorial_2digest__auth__postgres.html',1,'']]],
  ['disable_20middlewares_15',['Enable/disable middlewares',['../dd/d4b/md_en_2userver_2grpc_2middlewares__toggle.html',1,'']]],
  ['discovery_16',['uPg: Cluster topology discovery',['../da/d75/pg_topology.html',1,'']]],
  ['dist_5flock_5fcomponent_5fbase_17',['dist_lock_component_base',['../d8/df5/md_en_2components__schema_2mongo_2src_2storages_2mongo_2dist__lock__component__base.html',1,'dist_lock_component_base'],['../dc/d1d/md_en_2components__schema_2postgresql_2src_2storages_2postgres_2dist__lock__component__base.html',1,'dist_lock_component_base']]],
  ['distlocks_18',['Periodics and DistLocks',['../d7/dc4/md_en_2userver_2periodics.html',1,'']]],
  ['distro_20package_20maintainers_19',['Distro package maintainers',['../d1/d00/md_en_2userver_2distro__maintainers.html',1,'']]],
  ['dns_20',['Controlling DNS',['../dc/d72/md_en_2userver_2dns__control.html',1,'']]],
  ['dns_5fclient_21',['dns_client',['../d8/da4/md_en_2components__schema_2core_2static__configs_2dns__client.html',1,'']]],
  ['docker_20container_20for_20userver_22',['Building Docker container for userver',['../d7/df3/md__2data_2code_2userver_2scripts_2docker_2Readme.html',1,'']]],
  ['driver_23',['driver',['../dd/ddb/clickhouse_driver.html',1,'ClickHouse Driver'],['../d2/d5f/md_en_2userver_2mysql_2mysql__driver.html',1,'MySQL Driver'],['../dd/d8a/md_en_2userver_2sqlite_2sqlite__driver.html',1,'SQLite Driver'],['../de/de0/pg_driver.html',1,'uPg Driver']]],
  ['driver_20design_20and_20implementation_20details_24',['driver design and implementation details',['../dd/d32/md_en_2userver_2mysql_2design__and__details.html',1,'MySQL driver design and implementation details'],['../d4/df5/md_en_2userver_2sqlite_2design__and__details.html',1,'SQLite driver design and implementation details']]],
  ['driver_20writing_20guide_25',['Driver Writing Guide',['../de/ddb/md_en_2userver_2driver__guide.html',1,'']]],
  ['dump_20coroutines_20in_20runtime_26',['Dump coroutines in runtime',['../d7/d5b/md_en_2userver_2dump__coroutines.html',1,'']]],
  ['dump_5fconfigurator_27',['dump_configurator',['../df/ddb/md_en_2components__schema_2core_2src_2components_2dump__configurator.html',1,'']]],
  ['dumper_28',['dumper',['../d3/d4f/md_en_2components__schema_2core_2src_2dump_2dumper.html',1,'']]],
  ['dumps_29',['Local cache dumps',['../da/dd6/md_en_2userver_2cache__dumps.html',1,'']]],
  ['duplex_20server_20with_20metrics_20and_20spans_30',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['duplex_20server_20with_20static_20configs_20validation_31',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['dynamic_20config_32',['Dynamic config',['../d5/d46/md_en_2userver_2dynamic__config.html',1,'']]],
  ['dynamic_20config_20schemas_20list_33',['Dynamic config schemas list',['../db/d70/md_en_2dynamic__configs_2dynamic__configs.html',1,'']]],
  ['dynamic_20web_20pages_34',['Serving Static Content and Dynamic Web Pages',['../d2/d6d/md_en_2userver_2tutorial_2static__content.html',1,'']]],
  ['dynamic_5fdebug_5flog_35',['dynamic_debug_log',['../d7/dc7/md_en_2components__schema_2core_2src_2server_2handlers_2dynamic__debug__log.html',1,'']]]
];
