var searchData=
[
  ['ubuntu_2022_2004_0',['ubuntu-22.04',['../de/d9c/md_en_2deps_2ubuntu-22_804.html',1,'']]],
  ['ubuntu_2024_2004_1',['ubuntu-24.04',['../d5/d6a/md_en_2deps_2ubuntu-24_804.html',1,'']]],
  ['unit_20tests_20and_20benchmarks_2',['Unit Tests and Benchmarks',['../d4/d70/md_en_2userver_2testing.html',1,'']]],
  ['upg_20driver_3',['uPg Driver',['../de/de0/pg_driver.html',1,'']]],
  ['upg_3a_20automatic_20connection_20limit_4',['uPg: Automatic connection limit',['../d1/d60/md_en_2userver_2pg__connlimit__mode__auto.html',1,'']]],
  ['upg_3a_20cluster_20topology_20discovery_5',['uPg: Cluster topology discovery',['../da/d75/pg_topology.html',1,'']]],
  ['upg_3a_20postgres_20errors_6',['uPg: Postgres errors',['../d5/d8e/pg_errors.html',1,'']]],
  ['upg_3a_20postgresql_20user_20type_20mappings_7',['uPg: PostgreSQL user type mappings',['../df/d47/md_en_2userver_2pg__user__types.html',1,'']]],
  ['upg_3a_20running_20queries_8',['uPg: Running queries',['../da/d1c/pg_run_queries.html',1,'']]],
  ['upg_3a_20support_20for_20c_20strong_20typedef_20idiom_9',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../d3/ddf/pg_strong_typedef.html',1,'']]],
  ['upg_3a_20supported_20data_20types_10',['uPg: Supported data types',['../dd/dad/md_en_2userver_2pg__types.html',1,'']]],
  ['upg_3a_20transactions_11',['uPg: Transactions',['../db/dd8/pg_transactions.html',1,'']]],
  ['upg_3a_20typed_20postgresql_20results_12',['uPg: Typed PostgreSQL results',['../d2/d2f/pg_user_row_types.html',1,'']]],
  ['upg_3a_20working_20with_20result_20sets_13',['uPg: Working with result sets',['../db/db5/pg_process_results.html',1,'']]],
  ['uploads_20and_20multipart_20form_20data_20testing_14',['File uploads and multipart/form-data testing',['../df/d0f/md_en_2userver_2tutorial_2multipart__service.html',1,'']]],
  ['usage_15',['Guide on TaskProcessor Usage',['../db/d90/md_en_2userver_2task__processors__guide.html',1,'']]],
  ['used_20lru_20caches_20and_20expirable_20lru_20caches_16',['Least Recently Used (LRU) Caches and expirable LRU caches',['../d0/dd8/md_en_2userver_2lru__cache.html',1,'']]],
  ['user_20type_20mappings_17',['uPg: PostgreSQL user type mappings',['../df/d47/md_en_2userver_2pg__user__types.html',1,'']]],
  ['userver_18',['userver',['../index.html',1,'']]],
  ['userver_20s_20own_20samples_20tests_20and_20benchmarks_19',['Build instructions for userver&apos;s own samples, tests and benchmarks',['../df/d35/md_en_2userver_2build_2userver.html',1,'']]],
  ['userver_5fadd_5fsql_5flibrary_20',['Embedding SQL/YQL files via userver_add_sql_library',['../d6/de0/md_en_2userver_2sql__files.html',1,'']]],
  ['userver_5fbaggage_5fenabled_21',['USERVER_BAGGAGE_ENABLED',['../d7/dd9/md_en_2dynamic__configs_2USERVER__BAGGAGE__ENABLED.html',1,'']]],
  ['userver_5fcaches_22',['USERVER_CACHES',['../d6/d3e/md_en_2dynamic__configs_2USERVER__CACHES.html',1,'']]],
  ['userver_5fcancel_5fhandle_5frequest_5fby_5fdeadline_23',['USERVER_CANCEL_HANDLE_REQUEST_BY_DEADLINE',['../d0/d9d/md_en_2dynamic__configs_2USERVER__CANCEL__HANDLE__REQUEST__BY__DEADLINE.html',1,'']]],
  ['userver_5fdeadline_5fpropagation_5fenabled_24',['USERVER_DEADLINE_PROPAGATION_ENABLED',['../dc/da0/md_en_2dynamic__configs_2USERVER__DEADLINE__PROPAGATION__ENABLED.html',1,'']]],
  ['userver_5fdumps_25',['USERVER_DUMPS',['../d4/d89/md_en_2dynamic__configs_2USERVER__DUMPS.html',1,'']]],
  ['userver_5ffiles_5fcontent_5ftype_5fmap_26',['USERVER_FILES_CONTENT_TYPE_MAP',['../d2/d59/md_en_2dynamic__configs_2USERVER__FILES__CONTENT__TYPE__MAP.html',1,'']]],
  ['userver_5fgrpc_5fclient_5fenable_5fdeadline_5fpropagation_27',['USERVER_GRPC_CLIENT_ENABLE_DEADLINE_PROPAGATION',['../d7/d9e/md_en_2dynamic__configs_2USERVER__GRPC__CLIENT__ENABLE__DEADLINE__PROPAGATION.html',1,'']]],
  ['userver_5fgrpc_5fserver_5fcancel_5ftask_5fby_5fdeadline_28',['USERVER_GRPC_SERVER_CANCEL_TASK_BY_DEADLINE',['../d4/d84/md_en_2dynamic__configs_2USERVER__GRPC__SERVER__CANCEL__TASK__BY__DEADLINE.html',1,'']]],
  ['userver_5fhttp_5fproxy_29',['USERVER_HTTP_PROXY',['../d5/dc8/md_en_2dynamic__configs_2USERVER__HTTP__PROXY.html',1,'']]],
  ['userver_5flog_5fdynamic_5fdebug_30',['USERVER_LOG_DYNAMIC_DEBUG',['../d1/d57/md_en_2dynamic__configs_2USERVER__LOG__DYNAMIC__DEBUG.html',1,'']]],
  ['userver_5flog_5frequest_31',['USERVER_LOG_REQUEST',['../db/dd7/md_en_2dynamic__configs_2USERVER__LOG__REQUEST.html',1,'']]],
  ['userver_5flog_5frequest_5fheaders_32',['USERVER_LOG_REQUEST_HEADERS',['../de/d23/md_en_2dynamic__configs_2USERVER__LOG__REQUEST__HEADERS.html',1,'']]],
  ['userver_5flog_5frequest_5fheaders_5fwhitelist_33',['USERVER_LOG_REQUEST_HEADERS_WHITELIST',['../de/d72/md_en_2dynamic__configs_2USERVER__LOG__REQUEST__HEADERS__WHITELIST.html',1,'']]],
  ['userver_5flru_5fcaches_34',['USERVER_LRU_CACHES',['../d5/d7a/md_en_2dynamic__configs_2USERVER__LRU__CACHES.html',1,'']]],
  ['userver_5fno_5flog_5fspans_35',['USERVER_NO_LOG_SPANS',['../d7/db4/md_en_2dynamic__configs_2USERVER__NO__LOG__SPANS.html',1,'']]],
  ['userver_5frps_5fccontrol_36',['USERVER_RPS_CCONTROL',['../d1/d1b/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL.html',1,'']]],
  ['userver_5frps_5fccontrol_5factivated_5ffactor_5fmetric_37',['USERVER_RPS_CCONTROL_ACTIVATED_FACTOR_METRIC',['../da/d38/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL__ACTIVATED__FACTOR__METRIC.html',1,'']]],
  ['userver_5frps_5fccontrol_5fcustom_5fstatus_38',['USERVER_RPS_CCONTROL_CUSTOM_STATUS',['../d8/da3/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL__CUSTOM__STATUS.html',1,'']]],
  ['userver_5frps_5fccontrol_5fenabled_39',['USERVER_RPS_CCONTROL_ENABLED',['../d4/d4e/md_en_2dynamic__configs_2USERVER__RPS__CCONTROL__ENABLED.html',1,'']]],
  ['userver_5ftask_5fprocessor_5fprofiler_5fdebug_40',['USERVER_TASK_PROCESSOR_PROFILER_DEBUG',['../d9/d43/md_en_2dynamic__configs_2USERVER__TASK__PROCESSOR__PROFILER__DEBUG.html',1,'']]],
  ['userver_5ftask_5fprocessor_5fqos_41',['USERVER_TASK_PROCESSOR_QOS',['../d4/dc7/md_en_2dynamic__configs_2USERVER__TASK__PROCESSOR__QOS.html',1,'']]]
];
